package tara.dsl;

import java.util.Locale;

import static tara.lang.semantics.constraints.RuleFactory.*;

public class Analytics extends Tara {
	public Analytics() {
		def("").with(context("").has(component("Place", new tara.lang.model.rules.Size(0, 2147483647), tara.lang.model.Tag.TERMINAL_INSTANCE, tara.lang.model.Tag.MAIN), component("Vehicle", new tara.lang.model.rules.Size(0, 2147483647), tara.lang.model.Tag.TERMINAL_INSTANCE, tara.lang.model.Tag.MAIN), component("VehicleModel", new tara.lang.model.rules.Size(0, 2147483647), tara.lang.model.Tag.TERMINAL_INSTANCE, tara.lang.model.Tag.MAIN), component("Person", new tara.lang.model.rules.Size(0, 2147483647), tara.lang.model.Tag.TERMINAL_INSTANCE, tara.lang.model.Tag.MAIN), component("Supply", new tara.lang.model.rules.Size(0, 2147483647), tara.lang.model.Tag.TERMINAL_INSTANCE, tara.lang.model.Tag.MAIN), component("Charge", new tara.lang.model.rules.Size(0, 2147483647), tara.lang.model.Tag.TERMINAL_INSTANCE, tara.lang.model.Tag.MAIN), component("Mileage", new tara.lang.model.rules.Size(0, 2147483647), tara.lang.model.Tag.TERMINAL_INSTANCE, tara.lang.model.Tag.MAIN), component("PersonPatterns", new tara.lang.model.rules.Size(0, 2147483647), tara.lang.model.Tag.TERMINAL_INSTANCE, tara.lang.model.Tag.MAIN), component("PersonHomes", new tara.lang.model.rules.Size(0, 2147483647), tara.lang.model.Tag.TERMINAL_INSTANCE, tara.lang.model.Tag.MAIN), component("PersonWorks", new tara.lang.model.rules.Size(0, 2147483647), tara.lang.model.Tag.TERMINAL_INSTANCE, tara.lang.model.Tag.MAIN), component("PersonOthers", new tara.lang.model.rules.Size(0, 2147483647), tara.lang.model.Tag.TERMINAL_INSTANCE, tara.lang.model.Tag.MAIN), component("Vehicles", new tara.lang.model.rules.Size(0, 2147483647), tara.lang.model.Tag.TERMINAL_INSTANCE, tara.lang.model.Tag.MAIN), component("useCases", new tara.lang.model.rules.Size(0, 2147483647), tara.lang.model.Tag.TERMINAL_INSTANCE, tara.lang.model.Tag.MAIN), component("Query", new tara.lang.model.rules.Size(0, 2147483647), tara.lang.model.Tag.MAIN, tara.lang.model.Tag.TERMINAL_INSTANCE), component("Olap", new tara.lang.model.rules.Size(0, 2147483647), tara.lang.model.Tag.TERMINAL_INSTANCE, tara.lang.model.Tag.MAIN), component("Dashboard", new tara.lang.model.rules.Size(0, 2147483647), tara.lang.model.Tag.TERMINAL_INSTANCE, tara.lang.model.Tag.MAIN), component("Ticket", new tara.lang.model.rules.Size(0, 2147483647), tara.lang.model.Tag.MAIN, tara.lang.model.Tag.TERMINAL_INSTANCE), component("RestFunction", new tara.lang.model.rules.Size(0, 2147483647), tara.lang.model.Tag.MAIN, tara.lang.model.Tag.TERMINAL_INSTANCE), component("Indicator", new tara.lang.model.rules.Size(0, 2147483647), tara.lang.model.Tag.MAIN, tara.lang.model.Tag.TERMINAL_INSTANCE), component("Timeline", new tara.lang.model.rules.Size(0, 1), tara.lang.model.Tag.TERMINAL_INSTANCE, tara.lang.model.Tag.MAIN)).doc("sumus.Analytics", 0, ""));
		def("Place").with(context("Member", "Concept").has(facet("GeolocatedPlace", true)).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/sumus/Analytics/model/Main.tara", 4, ""));
		def("Vehicle").with(context("Member", "Concept").has(parameter("model", new tara.lang.model.rules.Size(1, 1), null, 0, new tara.lang.model.rules.variable.ReferenceRule(java.util.Arrays.asList("VehicleModel")), "TERMINAL")).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/sumus/Analytics/model/Main.tara", 5, ""));
		def("VehicleModel").with(context("Member", "Concept").has(parameter("autonomy", tara.lang.model.Primitive.DOUBLE, new tara.lang.model.rules.Size(1, 1), null, 0, null, "TERMINAL"), parameter("capacity", tara.lang.model.Primitive.DOUBLE, new tara.lang.model.rules.Size(1, 1), null, 1, null, "TERMINAL")).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/sumus/Analytics/model/Main.tara", 7, ""));
		def("Person").with(context("Member", "Concept").has(parameter("vehicle", new tara.lang.model.rules.Size(1, 1), null, 0, new tara.lang.model.rules.variable.ReferenceRule(java.util.Arrays.asList("Vehicle")), "TERMINAL"), parameter("home", new tara.lang.model.rules.Size(1, 1), null, 1, new tara.lang.model.rules.variable.ReferenceRule(java.util.Arrays.asList("Place")), "TERMINAL"), parameter("work", new tara.lang.model.rules.Size(1, 1), null, 2, new tara.lang.model.rules.variable.ReferenceRule(java.util.Arrays.asList("Place")), "TERMINAL"), parameter("other", new tara.lang.model.rules.Size(1, 1), null, 3, new tara.lang.model.rules.variable.ReferenceRule(java.util.Arrays.asList("Place")), "TERMINAL"), parameter("pattern", tara.lang.model.Primitive.STRING, new tara.lang.model.rules.Size(1, 1), null, 4, null, "TERMINAL")).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/sumus/Analytics/model/Main.tara", 10, ""));
		def("GeolocatedPlace").with(context("Geolocated", "Concept").has(name()).assume(isTerminalInstance(), isFacetInstance()).doc("/Users/oroncal/workspace/sandbox/sumus/Analytics/model/Main.tara", 17, ""));
		def("Supply").with(context("Fact", "Concept").has(parameter("place", new tara.lang.model.rules.Size(1, 1), null, 0, new tara.lang.model.rules.variable.ReferenceRule(java.util.Arrays.asList("Place")), "TERMINAL"), parameter("vehicle", new tara.lang.model.rules.Size(1, 1), null, 1, new tara.lang.model.rules.variable.ReferenceRule(java.util.Arrays.asList("Vehicle")), "TERMINAL"), parameter("person", new tara.lang.model.rules.Size(1, 1), null, 2, new tara.lang.model.rules.variable.ReferenceRule(java.util.Arrays.asList("Person")), "TERMINAL"), parameter("power", tara.lang.model.Primitive.DOUBLE, new tara.lang.model.rules.Size(1, 1), null, 3, null, "TERMINAL")).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/sumus/Analytics/model/Main.tara", 20, ""));
		def("Charge").with(context("Fact", "Concept").has(parameter("vehicle", new tara.lang.model.rules.Size(1, 1), null, 0, new tara.lang.model.rules.variable.ReferenceRule(java.util.Arrays.asList("Vehicle")), "TERMINAL"), parameter("person", new tara.lang.model.rules.Size(1, 1), null, 1, new tara.lang.model.rules.variable.ReferenceRule(java.util.Arrays.asList("Person")), "TERMINAL"), parameter("dayTime", tara.lang.model.Primitive.DOUBLE, new tara.lang.model.rules.Size(1, 1), null, 2, null, "TERMINAL")).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/sumus/Analytics/model/Main.tara", 25, ""));
		def("Mileage").with(context("Fact", "Concept").has(parameter("vehicle", new tara.lang.model.rules.Size(1, 1), null, 0, new tara.lang.model.rules.variable.ReferenceRule(java.util.Arrays.asList("Vehicle")), "TERMINAL"), parameter("person", new tara.lang.model.rules.Size(1, 1), null, 1, new tara.lang.model.rules.variable.ReferenceRule(java.util.Arrays.asList("Person")), "TERMINAL"), parameter("kilometers", tara.lang.model.Primitive.DOUBLE, new tara.lang.model.rules.Size(1, 1), null, 2, null, "TERMINAL")).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/sumus/Analytics/model/Main.tara", 29, ""));
		def("PersonPatterns").with(context("AutomaticCategorization", "Concept").has().assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/sumus/Analytics/model/Query.tara", 7, ""));
		def("PersonHomes").with(context("AutomaticCategorization", "Concept").has().assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/sumus/Analytics/model/Query.tara", 9, ""));
		def("PersonWorks").with(context("AutomaticCategorization", "Concept").has().assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/sumus/Analytics/model/Query.tara", 11, ""));
		def("PersonOthers").with(context("AutomaticCategorization", "Concept").has().assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/sumus/Analytics/model/Query.tara", 13, ""));
		def("Vehicles").with(context("AutomaticCategorization", "Concept").has().assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/sumus/Analytics/model/Query.tara", 15, ""));
		def("useCases").with(context("OriginGroup", "Concept").has(component("useCases.alwaysCharging", new tara.lang.model.rules.Size(0, 2147483647), tara.lang.model.Tag.TERMINAL_INSTANCE), component("useCases.onlyAtWork", new tara.lang.model.rules.Size(0, 2147483647), tara.lang.model.Tag.TERMINAL_INSTANCE), component("useCases.onlyAtHome", new tara.lang.model.rules.Size(0, 2147483647), tara.lang.model.Tag.TERMINAL_INSTANCE)).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/sumus/Analytics/model/Query.tara", 32, ""));
		def("useCases.alwaysCharging").with(context("OriginGroup.Origin", "Concept").has().assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/sumus/Analytics/model/Query.tara", 33, ""));
		def("Dashboard").with(context("Concept").has(component("Dashboard.Heatmap", new tara.lang.model.rules.Size(0, 2147483647)), parameter("label", tara.lang.model.Primitive.STRING, new tara.lang.model.rules.Size(1, 1), null, 0, null), parameter("layout", tara.lang.model.Primitive.STRING, new tara.lang.model.rules.Size(0, 1), null, 1, null)).assume(isTerminalInstance(), isMain()));
		def("Dashboard.Chart.Display.ColorScheme").with(context("Concept").has(parameter("colors", tara.lang.model.Primitive.INTEGER, new tara.lang.model.rules.Size(1, 2147483647), null, 0, null)).assume(isTerminalInstance()));
		def("Indicator.Aggregate").with(context("Concept").has(parameter("recordType", new tara.lang.model.rules.Size(1, 1), null, 0, new tara.lang.model.rules.variable.ReferenceRule(java.util.Arrays.asList("Record", "Member", "Fact"))), parameter("attribute", tara.lang.model.Primitive.FUNCTION, new tara.lang.model.rules.Size(1, 1), null, 1, new tara.lang.model.rules.variable.NativeRule("Attribute", "public Object get(tara.magritte.Declaration item)", "Sumus"))).assume(isTerminalInstance()));
		def("Indicator.Analyze").with(context("Concept").has(parameter("categorizations", new tara.lang.model.rules.Size(1, 2147483647), null, 0, new tara.lang.model.rules.variable.ReferenceRule(java.util.Arrays.asList("AutomaticCategorization", "Categorization", "PoliticalCategorization")))).assume(isTerminalInstance()));
		def("Dashboard.Heatmap").with(context("Concept").has(component("Dashboard.Chart.Display", new tara.lang.model.rules.Size(0, 2147483647)), parameter("indicator", new tara.lang.model.rules.Size(1, 1), null, 0, new tara.lang.model.rules.variable.ReferenceRule(java.util.Arrays.asList("Indicator")))).assume(isTerminalInstance()));
		def("Olap.ZoomGroup").with(context("Concept").has(component("Olap.ZoomGroup.Zoom", new tara.lang.model.rules.Size(0, 2147483647))).assume(isTerminalInstance()));
		def("Ticket").with(context("Concept").has(parameter("label", tara.lang.model.Primitive.STRING, new tara.lang.model.rules.Size(1, 1), null, 0, null), parameter("origin", new tara.lang.model.rules.Size(0, 1), null, 1, new tara.lang.model.rules.variable.ReferenceRule(java.util.Arrays.asList("OriginGroup.Origin"))), parameter("indicator", new tara.lang.model.rules.Size(1, 1), null, 2, new tara.lang.model.rules.variable.ReferenceRule(java.util.Arrays.asList("Indicator"))), parameter("aggregation", tara.lang.model.Primitive.WORD, new tara.lang.model.rules.Size(1, 1), null, 3, new tara.lang.model.rules.variable.WordRule(java.util.Arrays.asList("Average", "Sum", "Max", "Min", "Count"), "Aggregation"))).assume(isMain(), isTerminalInstance()));
		def("RestFunction").with(context("Concept").has(parameter("url", tara.lang.model.Primitive.STRING, new tara.lang.model.rules.Size(1, 1), null, 0, null), parameter("response", tara.lang.model.Primitive.FUNCTION, new tara.lang.model.rules.Size(1, 1), null, 1, new tara.lang.model.rules.variable.NativeRule("QueryHandler", "public void handle(Map parameters, javax.servlet.http.HttpServletResponse servletResponse)", "Sumus"))).assume(isMain(), isTerminalInstance()));
		def("Dashboard.Chart.Display").with(context("Concept").has(component("Dashboard.Chart.Display.ColorScheme", new tara.lang.model.rules.Size(0, 1)), parameter("title", tara.lang.model.Primitive.STRING, new tara.lang.model.rules.Size(1, 1), null, 0, null)).assume(isTerminalInstance()));
		def("Indicator").with(context("Concept").has(component("Indicator.Aggregate", new tara.lang.model.rules.Size(1, 1)), component("Indicator.Analyze", new tara.lang.model.rules.Size(1, 1)), parameter("label", tara.lang.model.Primitive.STRING, new tara.lang.model.rules.Size(1, 1), null, 0, null), parameter("scales", tara.lang.model.Primitive.WORD, new tara.lang.model.rules.Size(1, 2147483647), null, 1, new tara.lang.model.rules.variable.WordRule(java.util.Arrays.asList("Year", "Quarter", "Month", "Week", "Day", "SixHours", "Hour", "FifteenMinutes", "Minute", "Second"), "TimeScale"))).assume(isMain(), isTerminalInstance()));
		def("Timeline").with(context("Concept").has(parameter("from", tara.lang.model.Primitive.DATE, new tara.lang.model.rules.Size(1, 1), null, 0, null), parameter("to", tara.lang.model.Primitive.DATE, new tara.lang.model.rules.Size(1, 1), null, 1, null), parameter("scales", tara.lang.model.Primitive.WORD, new tara.lang.model.rules.Size(1, 2147483647), null, 2, new tara.lang.model.rules.variable.WordRule(java.util.Arrays.asList("Year", "Quarter", "Month", "Week", "Day", "SixHours", "Hour", "FifteenMinutes", "Minute", "Second"), "TimeScale"))).assume(isTerminalInstance(), isMain()));
		def("Olap.ZoomGroup.Zoom").with(context("Concept").has(parameter("scale", tara.lang.model.Primitive.WORD, new tara.lang.model.rules.Size(1, 1), null, 0, new tara.lang.model.rules.variable.WordRule(java.util.Arrays.asList("Year", "Quarter", "Month", "Week", "Day", "SixHours", "Hour", "FifteenMinutes", "Minute", "Second"), "TimeScale")), parameter("levels", tara.lang.model.Primitive.INTEGER, new tara.lang.model.rules.Size(1, 2147483647), null, 1, null)).assume(isTerminalInstance()));
	}


	@Override
	public String languageName() {
		return "Analytics";
	}

	@Override
	public Locale locale() {
		return Locale.ENGLISH;
	}

	@Override
	public boolean isTerminalLanguage() {
		return true;
	}
}