package tara.dsl;

import tara.language.model.Tag;

import java.util.Locale;

import static tara.language.semantics.constraints.RuleFactory.*;

public class Externa extends Tara {
	public Externa() {
		in("").def(context("").allow(multiple("TrabajoPreventivo", Tag.TERMINAL_INSTANCE, Tag.MAIN), multiple("Lugar", Tag.TERMINAL_INSTANCE, Tag.MAIN), multiple("Edificio", Tag.TERMINAL_INSTANCE, Tag.MAIN), multiple("Instalacion", Tag.TERMINAL_INSTANCE, Tag.MAIN), multiple("NotificacionIncidencia", Tag.TERMINAL_INSTANCE, Tag.MAIN), multiple("Trabajos", Tag.TERMINAL_INSTANCE, Tag.MAIN), multiple("TrabajoPreventivo", Tag.TERMINAL_INSTANCE, Tag.MAIN), multiple("TrabajoCorrectivo", Tag.TERMINAL_INSTANCE, Tag.MAIN), multiple("RoleCoordinador", Tag.TERMINAL_INSTANCE, Tag.MAIN), multiple("RoleAdministradorSistema", Tag.TERMINAL_INSTANCE, Tag.MAIN), multiple("RoleInspector", Tag.TERMINAL_INSTANCE, Tag.MAIN), multiple("RoleNotificador", Tag.TERMINAL_INSTANCE, Tag.MAIN), multiple("DialogoEncargoCorrectivo", Tag.TERMINAL_INSTANCE, Tag.MAIN), multiple("DialogoResultadoCorrectivo", Tag.TERMINAL_INSTANCE, Tag.MAIN), multiple("TrabajoCorrectivo", Tag.TERMINAL_INSTANCE, Tag.MAIN), multiple("EscritorioCoordinador", Tag.TERMINAL_INSTANCE, Tag.MAIN), multiple("EscritorioAdministradorSistema", Tag.TERMINAL_INSTANCE, Tag.MAIN), multiple("EscritorioInspector", Tag.TERMINAL_INSTANCE, Tag.MAIN), multiple("EscritorioNotificador", Tag.TERMINAL_INSTANCE, Tag.MAIN), multiple("Suministradores", Tag.TERMINAL_INSTANCE, Tag.MAIN), multiple("Piezas", Tag.TERMINAL_INSTANCE, Tag.MAIN), multiple("Preferencias", Tag.TERMINAL_INSTANCE, Tag.MAIN), multiple("Verificar", Tag.TERMINAL_INSTANCE, Tag.MAIN), multiple("ControlCalidad", Tag.TERMINAL_INSTANCE, Tag.MAIN), single("Inventario", Tag.SINGLE, Tag.TERMINAL_INSTANCE, Tag.MAIN), single("Configuracion", Tag.TERMINAL_INSTANCE, Tag.MAIN, Tag.SINGLE), multiple("Sequence"), multiple("Dictionary"), multiple("User"), name()).doc("monetv4.Externa", 0, ""));
		in("TrabajoPreventivo").def(context("Node", "Concept").allow(multiple("Node.View"), name()).require(_plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/preventivo/TrabajoPreventivo.tara", 5, ""));
		in("Inventario").def(context("Node", "Concept").allow(multiple("Node.View"), name()).require(_plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/Inventario.tara", 4, ""));
		in("Lugar").def(context("Node", "Concept").allow(multiple("Node.View"), name(), facet("Actuable")).require(_plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/Inventario.tara", 11, ""));
		in("Edificio").def(context("Node", "Concept").allow(multiple("Edificio.Equipamiento", Tag.TERMINAL_INSTANCE), multiple("Node.View"), name(), facet("Actuable"), facet("Operable")).require(_plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/Inventario.tara", 18, ""));
		in("Edificio.Equipamiento").def(context("Section", "Concept").allow(multiple("Field.View"), parameter("extensible", "boolean", false, null, 0, "", "TERMINAL_INSTANCE"), parameter("conditional", "boolean", false, null, 1, "", "TERMINAL_INSTANCE"), name(), facet("Operable")).require(_plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/Inventario.tara", 21, "Ejemplos de equipamiento: Extintor, Ascensor, etc"));
		in("Instalacion").def(context("Node", "Concept").allow(multiple("Instalacion.Componente", Tag.TERMINAL_INSTANCE), multiple("Node.View"), name(), facet("Actuable"), facet("Operable")).require(_plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/Inventario.tara", 28, ""));
		in("Instalacion.Componente").def(context("Section", "Concept").allow(multiple("Field.View"), parameter("extensible", "boolean", false, null, 0, "", "TERMINAL_INSTANCE"), parameter("conditional", "boolean", false, null, 1, "", "TERMINAL_INSTANCE"), name(), facet("Operable")).require(_plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/Inventario.tara", 31, "Ejemplos de componente: Monumento, Señal, Farola, Contenedor, Banco, Parque Infantil, Fuente, Calle"));
		in("Actuable").def(context("Facet", "Concept").require(_name(), _plate()).assume(isTerminalInstance(), isFacetInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/Inventario.tara", 37, ""));
		in("Operable").def(context("Facet", "Concept").require(_name(), _plate()).assume(isTerminalInstance(), isFacetInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/Inventario.tara", 47, ""));
		in("ClienteCorrectivo").def(context("Customer", "Concept").allow(multiple("ClienteCorrectivo.Ni", Tag.TERMINAL_INSTANCE, Tag.FEATURE_INSTANCE), multiple("ClienteCorrectivo.Nr", Tag.TERMINAL_INSTANCE, Tag.FEATURE_INSTANCE), parameter("expiration", "date", false, null, 0, "", "TERMINAL_INSTANCE"), name()).require(_plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/Clientes.tara", 3, ""));
		in("ClienteCorrectivo.Ni").def(context("Provider.Request", "Concept").allow(name()).require(_plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/Clientes.tara", 4, ""));
		in("ClienteCorrectivo.Nr").def(context("Provider.Response", "Concept").allow(name()).require(_plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/Clientes.tara", 5, ""));
		in("NotificacionIncidencia").def(context("Node", "Concept").allow(multiple("Node.View"), name()).require(_plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/Notificaciones.tara", 3, ""));
		in("Trabajos").def(context("Node", "Concept").allow(multiple("Node.View"), name()).require(_plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/Trabajos.tara", 8, ""));
		in("Trabajos.[annonymous@Toolbar].RealizarInforme").def(context("Entity.Toolbar.Operation", "Concept").allow(name()).require(_plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/Trabajos.tara", 11, ""));
		in("LineaTiempo").def(context("Timeline", "Concept").allow(multiple("Hecho", Tag.TERMINAL_INSTANCE), name()).require(_plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/Trabajos.tara", 27, ""));
		in("Hecho").def(context("Step", "Concept").allow(parameter("link", new String[]{"TrabajoCorrectivo", "TrabajoPreventivo"}, false, "", 0, "", "TERMINAL"), name()).require(_parameter("executed", "date", false, null, 0, "", "TERMINAL_INSTANCE"), _parameter("description", "string", false, null, 1, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/Trabajos.tara", 30, ""));
		in("Revision").def(context("Step", "Concept").allow(multiple("Revision.Fecha", Tag.TERMINAL_INSTANCE), multiple("Revision.FechaEnvioOtv", Tag.TERMINAL_INSTANCE), multiple("Revision.TiempoMedio", Tag.TERMINAL_INSTANCE), multiple("Revision.Orden", Tag.TERMINAL_INSTANCE), multiple("Revision.Resultado", Tag.TERMINAL_INSTANCE), multiple("Hecho", Tag.TERMINAL_INSTANCE), parameter("link", new String[]{"TrabajoCorrectivo", "TrabajoPreventivo"}, false, "", 0, "", "TERMINAL"), name()).require(_parameter("executed", "date", false, null, 0, "", "TERMINAL_INSTANCE"), _parameter("description", "string", false, null, 1, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/estados/Revision.tara", 11, ""));
		in("Revision.Fecha").def(context("Date", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "date", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/estados/Revision.tara", 12, ""));
		in("Revision.FechaEnvioOtv").def(context("Date", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "date", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/estados/Revision.tara", 13, ""));
		in("Revision.TiempoMedio").def(context("Number", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "double", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/estados/Revision.tara", 14, ""));
		in("Revision.Orden").def(context("File", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "file", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/estados/Revision.tara", 15, ""));
		in("Revision.Resultado").def(context("File", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "file", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/estados/Revision.tara", 16, ""));
		in("Revisando").def(context("State", "Concept").allow(multiple("State.View"), parameter("currentPlace", new String[]{"Place"}, false, null, 0, "", "TERMINAL_INSTANCE")).require(_name(), _plate()).assume(isTerminalInstance(), isFacetInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/estados/Revision.tara", 21, ""));
		in("RoleCoordinador").def(context("Role", "Concept").allow(parameter("to", "date", false, null, 0, "", "TERMINAL_INSTANCE"), name()).require(_parameter("from", "date", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/Roles.tara", 3, ""));
		in("RoleAdministradorSistema").def(context("Role", "Concept").allow(parameter("to", "date", false, null, 0, "", "TERMINAL_INSTANCE"), name()).require(_parameter("from", "date", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/Roles.tara", 7, ""));
		in("RoleInspector").def(context("Role", "Concept").allow(parameter("to", "date", false, null, 0, "", "TERMINAL_INSTANCE"), name()).require(_parameter("from", "date", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/Roles.tara", 11, ""));
		in("RoleNotificador").def(context("Role", "Concept").allow(parameter("to", "date", false, null, 0, "", "TERMINAL_INSTANCE"), name()).require(_parameter("from", "date", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/Roles.tara", 15, ""));
		in("ProveedorVerificacion").def(context("ExternalProvider", "Concept").allow(multiple("ProveedorVerificacion.Otv", Tag.TERMINAL_INSTANCE, Tag.FEATURE_INSTANCE), parameter("expiration", "date", false, null, 0, "", "TERMINAL_INSTANCE"), parameter("name", "string", false, null, 1, "", "TERMINAL_INSTANCE"), name()).require(_plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/Proveedores.tara", 4, ""));
		in("ProveedorVerificacion.Otv").def(context("Provider.Request", "Concept").allow(name()).require(_plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/Proveedores.tara", 5, ""));
		in("DialogoEncargoCorrectivo").def(context("Dialog", "Concept").allow(multiple("DialogoEncargoCorrectivo.FechaInicio", Tag.TERMINAL_INSTANCE), multiple("DialogoEncargoCorrectivo.FechaFinLimite", Tag.TERMINAL_INSTANCE), multiple("DialogoEncargoCorrectivo.Observaciones", Tag.TERMINAL_INSTANCE), multiple("DialogoEncargoCorrectivo.Urgente", Tag.TERMINAL_INSTANCE), multiple("DialogoEncargoCorrectivo.Adjuntos", Tag.TERMINAL_INSTANCE, Tag.FACET_INSTANCE), multiple("Dialog.View"), name()).require(_plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/Dialogos.tara", 3, ""));
		in("DialogoEncargoCorrectivo.FechaInicio").def(context("Date", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "date", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/Dialogos.tara", 4, ""));
		in("DialogoEncargoCorrectivo.FechaFinLimite").def(context("Date", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "date", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/Dialogos.tara", 5, ""));
		in("DialogoEncargoCorrectivo.Observaciones").def(context("Memo", "Concept").allow(multiple("Field.View"), parameter("value", "string", false, null, 0, "", "TERMINAL_INSTANCE"), name()).require(_plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/Dialogos.tara", 6, ""));
		in("DialogoEncargoCorrectivo.Urgente").def(context("Check", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "boolean", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/Dialogos.tara", 7, ""));
		in("DialogoEncargoCorrectivo.Adjuntos").def(context("File", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "file", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/Dialogos.tara", 8, ""));
		in("DialogoResultadoCorrectivo").def(context("Dialog", "Concept").allow(multiple("DialogoResultadoCorrectivo.FechaInicioReal", Tag.TERMINAL_INSTANCE), multiple("DialogoResultadoCorrectivo.FechaFinReal", Tag.TERMINAL_INSTANCE), multiple("DialogoResultadoCorrectivo.Responsable", Tag.TERMINAL_INSTANCE), multiple("DialogoResultadoCorrectivo.Observaciones", Tag.TERMINAL_INSTANCE), multiple("DialogoResultadoCorrectivo.Foto", Tag.TERMINAL_INSTANCE), multiple("DialogoResultadoCorrectivo.Adjuntos", Tag.TERMINAL_INSTANCE, Tag.FACET_INSTANCE), multiple("Dialog.View"), name()).require(_plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/Dialogos.tara", 13, ""));
		in("DialogoResultadoCorrectivo.FechaInicioReal").def(context("Date", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "date", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/Dialogos.tara", 14, ""));
		in("DialogoResultadoCorrectivo.FechaFinReal").def(context("Date", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "date", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/Dialogos.tara", 15, ""));
		in("DialogoResultadoCorrectivo.Responsable").def(context("Text", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "string", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/Dialogos.tara", 16, ""));
		in("DialogoResultadoCorrectivo.Observaciones").def(context("Memo", "Concept").allow(multiple("Field.View"), parameter("value", "string", false, null, 0, "", "TERMINAL_INSTANCE"), name()).require(_plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/Dialogos.tara", 18, ""));
		in("DialogoResultadoCorrectivo.Foto").def(context("Picture", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "file", false, null, 0, "[jpgpng]##Monet", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/Dialogos.tara", 19, ""));
		in("DialogoResultadoCorrectivo.Adjuntos").def(context("File", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "file", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/Dialogos.tara", 20, ""));
		in("TrabajoCorrectivo").def(context("Node", "Concept").allow(multiple("TrabajoCorrectivo.CreadaPor", Tag.TERMINAL_INSTANCE), multiple("TrabajoCorrectivo.CodigoIncidencia", Tag.TERMINAL_INSTANCE), multiple("TrabajoCorrectivo.CodigoNotificacionIncidencia", Tag.TERMINAL_INSTANCE, Tag.FACET_INSTANCE), multiple("TrabajoCorrectivo.Foto", Tag.TERMINAL_INSTANCE, Tag.FACET_INSTANCE), multiple("TrabajoCorrectivo.CampoActuable", Tag.TERMINAL_INSTANCE), multiple("TrabajoCorrectivo.FechaCreacion", Tag.TERMINAL_INSTANCE), multiple("TrabajoCorrectivo.FechaIncidencia", Tag.TERMINAL_INSTANCE), multiple("TrabajoCorrectivo.FechaModificacion", Tag.TERMINAL_INSTANCE), multiple("TrabajoCorrectivo.Origen", Tag.TERMINAL_INSTANCE), multiple("TrabajoCorrectivo.Prioridad", Tag.TERMINAL_INSTANCE), multiple("TrabajoCorrectivo.Urgente", Tag.TERMINAL_INSTANCE), multiple("TrabajoCorrectivo.ObjetoPadre", Tag.TERMINAL_INSTANCE), multiple("TrabajoCorrectivo.RegistroEntrada", Tag.TERMINAL_INSTANCE), multiple("TrabajoCorrectivo.RegistroSalida", Tag.TERMINAL_INSTANCE), multiple("TrabajoCorrectivo.TipoIncidencia", Tag.TERMINAL_INSTANCE, Tag.FACET_INSTANCE), multiple("TrabajoCorrectivo.Descripcion", Tag.TERMINAL_INSTANCE), multiple("TrabajoCorrectivo.Unidad", Tag.TERMINAL_INSTANCE), multiple("TrabajoCorrectivo.Estado", Tag.TERMINAL_INSTANCE, Tag.FACET_INSTANCE), multiple("TrabajoCorrectivo.AdjuntosIncidencia", Tag.TERMINAL_INSTANCE, Tag.FACET_INSTANCE), multiple("TrabajoCorrectivo.TipoIcc", Tag.TERMINAL_INSTANCE), multiple("TrabajoCorrectivo.ImagenMapa", Tag.TERMINAL_INSTANCE), multiple("Node.View"), name(), facet("Revisando").allow(multiple("State.View")), facet("ServicioNotificacion").allow(multiple("ClienteCorrectivo", Tag.TERMINAL_INSTANCE), multiple("ProveedorVerificacion", Tag.TERMINAL_INSTANCE), multiple("LineaTiempo", Tag.TERMINAL_INSTANCE), multiple("Auditory"), multiple("Task.Suggestion"))).require(_plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Trabajo.tara", 8, ""));
		in("TrabajoCorrectivo.CreadaPor").def(context("Text", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "string", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Trabajo.tara", 14, ""));
		in("TrabajoCorrectivo.CodigoIncidencia").def(context("Serial", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "string", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Trabajo.tara", 15, ""));
		in("TrabajoCorrectivo.CodigoNotificacionIncidencia").def(context("Text", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "string", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Trabajo.tara", 16, ""));
		in("TrabajoCorrectivo.Foto").def(context("Picture", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "file", false, null, 0, "[jpgpng]##Monet", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Trabajo.tara", 17, ""));
		in("TrabajoCorrectivo.CampoActuable").def(context("Link", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", new String[]{"Actuable"}, false, null, 0, "", "TERMINAL"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Trabajo.tara", 18, ""));
		in("TrabajoCorrectivo.FechaCreacion").def(context("Date", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "date", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Trabajo.tara", 24, ""));
		in("TrabajoCorrectivo.FechaIncidencia").def(context("Date", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "date", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Trabajo.tara", 26, ""));
		in("TrabajoCorrectivo.FechaModificacion").def(context("Date", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "date", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Trabajo.tara", 27, ""));
		in("TrabajoCorrectivo.Origen").def(context("Select", "Concept").allow(multiple("Field.View"), multiple("Dictionary"), multiple("Select.SelectView"), name()).require(_parameter("value", new String[]{"Dictionary.Term"}, false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Trabajo.tara", 29, ""));
		in("TrabajoCorrectivo.Prioridad").def(context("Select", "Concept").allow(multiple("Field.View"), multiple("Dictionary"), multiple("Select.SelectView"), name()).require(_parameter("value", new String[]{"Dictionary.Term"}, false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Trabajo.tara", 34, ""));
		in("TrabajoCorrectivo.Urgente").def(context("Check", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "boolean", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Trabajo.tara", 38, ""));
		in("TrabajoCorrectivo.ObjetoPadre").def(context("Text", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "string", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Trabajo.tara", 39, ""));
		in("TrabajoCorrectivo.RegistroEntrada").def(context("Text", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "string", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Trabajo.tara", 40, ""));
		in("TrabajoCorrectivo.RegistroSalida").def(context("Text", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "string", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Trabajo.tara", 41, ""));
		in("TrabajoCorrectivo.TipoIncidencia").def(context("Select", "Concept").allow(multiple("Field.View"), multiple("Dictionary"), multiple("Select.SelectView"), name()).require(_parameter("value", new String[]{"Dictionary.Term"}, false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Trabajo.tara", 42, ""));
		in("TrabajoCorrectivo.Descripcion").def(context("Memo", "Concept").allow(multiple("Field.View"), parameter("value", "string", false, null, 0, "", "TERMINAL_INSTANCE"), name()).require(_plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Trabajo.tara", 43, ""));
		in("TrabajoCorrectivo.Unidad").def(context("Text", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "string", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Trabajo.tara", 44, ""));
		in("TrabajoCorrectivo.Estado").def(context("Select", "Concept").allow(multiple("Field.View"), multiple("Dictionary"), multiple("Select.SelectView"), name()).require(_parameter("value", new String[]{"Dictionary.Term"}, false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Trabajo.tara", 45, ""));
		in("TrabajoCorrectivo.AdjuntosIncidencia").def(context("File", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "file", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Trabajo.tara", 46, ""));
		in("TrabajoCorrectivo.TipoIcc").def(context("Text", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "string", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Trabajo.tara", 47, ""));
		in("TrabajoCorrectivo.ImagenMapa").def(context("Picture", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "file", false, null, 0, "[jpgpng]##Monet", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Trabajo.tara", 48, ""));
		in("ServicioNotificacion").def(context("Service", "Concept").allow(multiple("ClienteCorrectivo", Tag.TERMINAL_INSTANCE), multiple("ProveedorVerificacion", Tag.TERMINAL_INSTANCE), multiple("Auditory"), multiple("Task.Suggestion"), parameter("urgent", "boolean", false, null, 0, "", "TERMINAL_INSTANCE"), parameter("comments", "string", false, null, 1, "", "TERMINAL_INSTANCE"), parameter("status:word", new String[]{"[Created, Waiting, Pending, Finished, Aborted]"}, false, null, 2, "", "TERMINAL_INSTANCE")).require(_single("LineaTiempo"), _name(), _plate()).assume(isTerminalInstance(), isFacetInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Trabajo.tara", 81, ""));
		in("EscritorioCoordinador").def(context("Node", "Concept").allow(multiple("Node.View"), name()).require(_plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/Entornos.tara", 12, ""));
		in("EscritorioAdministradorSistema").def(context("Node", "Concept").allow(multiple("Node.View"), name()).require(_plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/Entornos.tara", 21, ""));
		in("EscritorioInspector").def(context("Node", "Concept").allow(multiple("Node.View"), name()).require(_plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/Entornos.tara", 28, ""));
		in("EscritorioNotificador").def(context("Node", "Concept").allow(multiple("Node.View"), name()).require(_plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/Entornos.tara", 35, ""));
		in("Suministradores").def(context("Node", "Concept").allow(multiple("Node.View"), name()).require(_plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/Maestros.tara", 3, ""));
		in("Piezas").def(context("Node", "Concept").allow(multiple("Node.View"), name()).require(_plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/Maestros.tara", 6, ""));
		in("Preferencias").def(context("Node", "Concept").allow(multiple("Node.View"), name()).require(_plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/Maestros.tara", 9, ""));
		in("Verificar").def(context("Node", "Concept").allow(multiple("Verificar.Imagen", Tag.TERMINAL_INSTANCE, Tag.FACET_INSTANCE), multiple("Verificar.Observaciones", Tag.TERMINAL_INSTANCE), multiple("Verificar.FechaInicio", Tag.TERMINAL_INSTANCE), multiple("Verificar.FechaFin", Tag.TERMINAL_INSTANCE), multiple("Verificar.FirmaOperario", Tag.TERMINAL_INSTANCE), multiple("Verificar.Verificado", Tag.TERMINAL_INSTANCE), multiple("Node.View"), name(), facet("JobVerificar").allow(multiple("Auditory"), multiple("Task.Suggestion"))).require(_plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Jobs.tara", 3, ""));
		in("Verificar.Imagen").def(context("Picture", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "file", false, null, 0, "[jpgpng]##Monet", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Jobs.tara", 4, ""));
		in("Verificar.Observaciones").def(context("Memo", "Concept").allow(multiple("Field.View"), parameter("value", "string", false, null, 0, "", "TERMINAL_INSTANCE"), name()).require(_plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Jobs.tara", 5, ""));
		in("Verificar.FechaInicio").def(context("Date", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "date", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Jobs.tara", 6, ""));
		in("Verificar.FechaFin").def(context("Date", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "date", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Jobs.tara", 7, ""));
		in("Verificar.FirmaOperario").def(context("Picture", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "file", false, null, 0, "[jpgpng]##Monet", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Jobs.tara", 8, ""));
		in("Verificar.Verificado").def(context("Check", "Concept").allow(multiple("Field.View"), name()).require(_parameter("value", "boolean", false, null, 0, "", "TERMINAL_INSTANCE"), _plate()).assume(isTerminalInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Jobs.tara", 9, ""));
		in("JobVerificar").def(context("Job", "Concept").allow(multiple("Auditory"), multiple("Task.Suggestion"), parameter("urgent", "boolean", false, null, 0, "", "TERMINAL_INSTANCE"), parameter("comments", "string", false, null, 1, "", "TERMINAL_INSTANCE"), parameter("status:word", new String[]{"[Created, Waiting, Pending, Finished, Aborted]"}, false, null, 2, "", "TERMINAL_INSTANCE")).require(_name(), _plate()).assume(isTerminalInstance(), isFacetInstance()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/trabajos/correctivo/Jobs.tara", 16, ""));
		in("ControlCalidad").def(context("Node", "Concept").allow(multiple("Node.View"), name()).require(_plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/ControlCalidad.tara", 3, ""));
		in("Configuracion").def(context("Distribution", "Concept").allow(parameter("soloEjecucion", "boolean", false, "", 0, "", "TERMINAL"), parameter("tipoRevision:word", new String[]{"Externa", "Interna", "InternaEnCampo", "SinRevision"}, false, "Externa,Interna,InternaEnCampo,SinRevision", 1, "", "TERMINAL"), name()).require(_plate()).assume(isTerminalInstance(), isMain()).doc("/Users/oroncal/workspace/sandbox/monetv4/Externa/model/Configuracion.tara", 3, ""));
		in("RevisionList").def(context("Concept").allow(name()).require().assume(isFacetInstance(), isTerminalInstance()));
		in("History").def(context("Concept").allow(name(), parameter("store", "string", false, null, 0, "##Monet")).require(_parameter("store", "string", false, null, 0, "##Monet")).assume(isFacetInstance(), isTerminalInstance()));
		in("Assistant").def(context("Concept").allow(multiple("FieldView.IsDefault"), multiple("Assistant.Step"), name()).require().assume(isTerminalInstance(), isFacetInstance()));
		in("PrototypeList").def(context("Concept").allow(multiple("Set.Sort"), parameter("mode:word", new String[]{"Table", "List", "Document"}, false, null, 0, ""), parameter("filter", "native", false, null, 1, "Filter#public boolean accept(monet.Entry entry)#Monet"), parameter("select", "native", false, null, 2, "Select#public boolean accept(monet.Entry entry)#Monet"), name(), parameter("nature:word", new String[]{"Shared", "Owned"}, false, null, 3, "")).require(_parameter("nature:word", new String[]{"Shared", "Owned"}, false, null, 3, "")).assume(isTerminalInstance(), isFacetInstance()));
		in("Field.View").def(context("Concept").allow(parameter("refresh", "native", false, null, 0, "Action#public void execute()#Monet"), name(), facet("PlaceMap"), facet("Table"), facet("Poll"), facet("Collection"), facet("History"), facet("Catalog")).require().assume(isTerminalInstance()));
		in("ThesaurusLink").def(context("Concept").allow(name(), parameter("thesaurus", new String[]{"Dictionary"}, true, null, 0, "")).require(_parameter("thesaurus", new String[]{"Dictionary"}, true, null, 0, "")).assume(isTerminalInstance(), isFacetInstance()));
		in("State.View.HideBreadCrumbs").def(context("Concept").allow(name()).require().assume(isTerminalInstance()));
		in("Folder").def(context("Concept").allow(parameter("documents", new String[]{"Document"}, true, null, 0, ""), parameter("files", new String[]{"Revision.Orden", "Revision.Resultado", "DialogoEncargoCorrectivo.Adjuntos", "DialogoResultadoCorrectivo.Adjuntos", "TrabajoCorrectivo.AdjuntosIncidencia"}, true, null, 1, ""), parameter("pictures", new String[]{"DialogoResultadoCorrectivo.Foto", "TrabajoCorrectivo.Foto", "TrabajoCorrectivo.ImagenMapa", "Verificar.Imagen", "Verificar.FirmaOperario"}, true, null, 2, ""), name()).require().assume(isFacetInstance(), isTerminalInstance()));
		in("PlaceMap").def(context("Concept").allow(multiple("Set.Sort"), parameter("mode:word", new String[]{"Table", "List", "Document"}, false, null, 0, ""), parameter("filter", "native", false, null, 1, "Filter#public boolean accept(monet.Entry entry)#Monet"), parameter("select", "native", false, null, 2, "Select#public boolean accept(monet.Entry entry)#Monet"), name()).require().assume(isTerminalInstance(), isFacetInstance()));
		in("Auditory").def(context("Concept").allow(name(), parameter("createDate", "date", false, null, 0, "##Monet"), parameter("startDate", "date", false, null, 1, "##Monet"), parameter("endDate", "date", false, null, 2, "##Monet")).require(_parameter("createDate", "date", false, null, 0, "##Monet"), _parameter("startDate", "date", false, null, 1, "##Monet"), _parameter("endDate", "date", false, null, 2, "##Monet")).assume(isTerminalInstance()));
		in("Dictionary.FromCollectable").def(context("Concept").allow(name(), parameter("type", new String[]{"Node"}, false, null, 0, "")).require(_parameter("type", new String[]{"Node"}, false, null, 0, "")).assume(isTerminalInstance()));
		in("Table").def(context("Concept").allow(multiple("FieldView.IsDefault"), name()).require().assume(isTerminalInstance(), isFacetInstance()));
		in("Node.View").def(context("Concept").allow(single("Node.View.IsDefault"), single("Node.View.HideBreadCrumbs"), parameter("label", "string", false, null, 0, "##Monet"), parameter("help", "file", false, null, 1, "##Monet"), parameter("refresh", "native", false, null, 2, "Action#public void execute()#Monet"), name(), facet("Form"), facet("RevisionList"), facet("HeatMap"), facet("ThesaurusLink"), facet("Folder"), facet("Catalog"), facet("PlaceMap"), facet("EntityLink"), facet("ExtendedForm"), facet("Assistant"), facet("PagePreview"), facet("PrototypeList"), facet("Poll"), facet("Collection"), facet("FollowerList")).require().assume(isTerminalInstance()));
		in("FieldView.IsDefault").def(context("Concept").allow(name()).require().assume(isTerminalInstance()));
		in("Initial").def(context("Concept").allow(name()).require().assume(isFacetInstance(), isTerminalInstance()));
		in("Place").def(context("Concept").allow(parameter("requireConfirmation", "boolean", false, null, 1, "##Monet"), parameter("enableBackButton", "native", false, null, 2, "Check#public boolean execute()#Monet"), parameter("onBack", "native", false, null, 3, "Event#public void execute()#Monet"), name(), facet("Initial"), facet("Terminal"), parameter("label", "string", false, null, 0, "##Monet")).require(_parameter("label", "string", false, null, 0, "##Monet")).assume(isTerminalInstance()));
		in("Task.Suggestion").def(context("Concept").allow(name(), parameter("startDate", "date", false, null, 0, "##Monet"), parameter("endDate", "date", false, null, 1, "##Monet")).require(_parameter("startDate", "date", false, null, 0, "##Monet"), _parameter("endDate", "date", false, null, 1, "##Monet")).assume(isTerminalInstance()));
		in("State.View.IsDefault").def(context("Concept").allow(name()).require().assume(isTerminalInstance()));
		in("HeatMap").def(context("Concept").allow(multiple("Set.Sort"), parameter("mode:word", new String[]{"Table", "List", "Document"}, false, null, 0, ""), parameter("filter", "native", false, null, 1, "Filter#public boolean accept(monet.Entry entry)#Monet"), parameter("select", "native", false, null, 2, "Select#public boolean accept(monet.Entry entry)#Monet"), name()).require().assume(isTerminalInstance(), isFacetInstance()));
		in("Set.Sort").def(context("Concept").allow(parameter("mode:word", new String[]{"Ascendant", "Descendant"}, false, null, 1, ""), name(), parameter("fields", new String[]{"DialogoEncargoCorrectivo.Urgente", "TrabajoCorrectivo.Urgente", "Verificar.Verificado", "DialogoResultadoCorrectivo.Responsable", "TrabajoCorrectivo.CreadaPor", "TrabajoCorrectivo.CodigoNotificacionIncidencia", "TrabajoCorrectivo.ObjetoPadre", "TrabajoCorrectivo.RegistroEntrada", "TrabajoCorrectivo.RegistroSalida", "TrabajoCorrectivo.Unidad", "TrabajoCorrectivo.TipoIcc", "Edificio.Equipamiento", "Instalacion.Componente", "Revision.Fecha", "Revision.FechaEnvioOtv", "DialogoEncargoCorrectivo.FechaInicio", "DialogoEncargoCorrectivo.FechaFinLimite", "DialogoResultadoCorrectivo.FechaInicioReal", "DialogoResultadoCorrectivo.FechaFinReal", "TrabajoCorrectivo.FechaCreacion", "TrabajoCorrectivo.FechaIncidencia", "TrabajoCorrectivo.FechaModificacion", "Verificar.FechaInicio", "Verificar.FechaFin", "TrabajoCorrectivo.CodigoIncidencia", "Revision.TiempoMedio", "DialogoResultadoCorrectivo.Foto", "TrabajoCorrectivo.Foto", "TrabajoCorrectivo.ImagenMapa", "Verificar.Imagen", "Verificar.FirmaOperario", "TrabajoCorrectivo.Origen", "TrabajoCorrectivo.Prioridad", "TrabajoCorrectivo.TipoIncidencia", "TrabajoCorrectivo.Estado", "Revision.Orden", "Revision.Resultado", "DialogoEncargoCorrectivo.Adjuntos", "DialogoResultadoCorrectivo.Adjuntos", "TrabajoCorrectivo.AdjuntosIncidencia", "DialogoEncargoCorrectivo.Observaciones", "DialogoResultadoCorrectivo.Observaciones", "TrabajoCorrectivo.Descripcion", "Verificar.Observaciones", "TrabajoCorrectivo.CampoActuable"}, true, null, 0, "")).require(_parameter("fields", new String[]{"Position", "Check", "Text", "Section", "Date", "Serial", "Number", "Picture", "Video", "Select", "File", "Memo", "Link"}, true, null, 0, "")).assume(isTerminalInstance()));
		in("Dialog.View").def(context("Concept").allow(parameter("label", "string", false, null, 0, "##Monet"), parameter("refresh", "native", false, null, 1, "Action#public void execute()#Monet"), name(), facet("Form"), facet("ExtendedForm"), facet("Poll")).require().assume(isTerminalInstance()));
		in("State.View").def(context("Concept").allow(single("State.View.IsDefault"), single("State.View.HideBreadCrumbs"), parameter("help", "file", false, null, 1, "##Monet"), parameter("refresh", "native", false, null, 2, "Action#public void execute()#Monet"), name(), facet("PlaceMap"), facet("PagePreview"), facet("Collection"), facet("HeatMap"), facet("Folder"), facet("Catalog"), parameter("label", "string", false, null, 0, "##Monet")).require(_parameter("label", "string", false, null, 0, "##Monet")).assume(isTerminalInstance()));
		in("Sequence").def(context("Concept").allow(parameter("value", "integer", false, null, 0, "##Monet"), name()).require().assume(isMain(), isTerminalInstance()));
		in("Catalog").def(context("Concept").allow(multiple("Set.Sort"), parameter("mode:word", new String[]{"Table", "List", "Document"}, false, null, 0, ""), parameter("filter", "native", false, null, 1, "Filter#public boolean accept(monet.Entry entry)#Monet"), parameter("select", "native", false, null, 2, "Select#public boolean accept(monet.Entry entry)#Monet"), parameter("historyStore", "string", false, null, 3, "##Monet"), name()).require().assume(isTerminalInstance(), isFacetInstance()));
		in("Assistant.Step").def(context("Concept").allow(parameter("layout", "string", false, null, 2, "##Monet"), parameter("multiple", "boolean", false, null, 3, "##Monet"), parameter("capturePosition", "boolean", false, null, 4, "##Monet"), parameter("captureDate", "boolean", false, null, 5, "##Monet"), name(), parameter("label", "string", false, null, 0, "##Monet"), parameter("fields", new String[]{"DialogoEncargoCorrectivo.Urgente", "TrabajoCorrectivo.Urgente", "Verificar.Verificado", "DialogoResultadoCorrectivo.Responsable", "TrabajoCorrectivo.CreadaPor", "TrabajoCorrectivo.CodigoNotificacionIncidencia", "TrabajoCorrectivo.ObjetoPadre", "TrabajoCorrectivo.RegistroEntrada", "TrabajoCorrectivo.RegistroSalida", "TrabajoCorrectivo.Unidad", "TrabajoCorrectivo.TipoIcc", "Edificio.Equipamiento", "Instalacion.Componente", "Revision.Fecha", "Revision.FechaEnvioOtv", "DialogoEncargoCorrectivo.FechaInicio", "DialogoEncargoCorrectivo.FechaFinLimite", "DialogoResultadoCorrectivo.FechaInicioReal", "DialogoResultadoCorrectivo.FechaFinReal", "TrabajoCorrectivo.FechaCreacion", "TrabajoCorrectivo.FechaIncidencia", "TrabajoCorrectivo.FechaModificacion", "Verificar.FechaInicio", "Verificar.FechaFin", "TrabajoCorrectivo.CodigoIncidencia", "Revision.TiempoMedio", "DialogoResultadoCorrectivo.Foto", "TrabajoCorrectivo.Foto", "TrabajoCorrectivo.ImagenMapa", "Verificar.Imagen", "Verificar.FirmaOperario", "TrabajoCorrectivo.Origen", "TrabajoCorrectivo.Prioridad", "TrabajoCorrectivo.TipoIncidencia", "TrabajoCorrectivo.Estado", "Revision.Orden", "Revision.Resultado", "DialogoEncargoCorrectivo.Adjuntos", "DialogoResultadoCorrectivo.Adjuntos", "TrabajoCorrectivo.AdjuntosIncidencia", "DialogoEncargoCorrectivo.Observaciones", "DialogoResultadoCorrectivo.Observaciones", "TrabajoCorrectivo.Descripcion", "Verificar.Observaciones", "TrabajoCorrectivo.CampoActuable"}, true, null, 1, "")).require(_parameter("label", "string", false, null, 0, "##Monet"), _parameter("fields", new String[]{"Position", "Check", "Text", "Section", "Date", "Serial", "Number", "Picture", "Video", "Select", "File", "Memo", "Link"}, true, null, 1, "")).assume(isTerminalInstance()));
		in("ExtendedForm").def(context("Concept").allow(multiple("FieldView.IsDefault"), parameter("layout", "string", false, null, 1, "##Monet"), name(), parameter("fields", new String[]{"DialogoEncargoCorrectivo.Urgente", "TrabajoCorrectivo.Urgente", "Verificar.Verificado", "DialogoResultadoCorrectivo.Responsable", "TrabajoCorrectivo.CreadaPor", "TrabajoCorrectivo.CodigoNotificacionIncidencia", "TrabajoCorrectivo.ObjetoPadre", "TrabajoCorrectivo.RegistroEntrada", "TrabajoCorrectivo.RegistroSalida", "TrabajoCorrectivo.Unidad", "TrabajoCorrectivo.TipoIcc", "Edificio.Equipamiento", "Instalacion.Componente", "Revision.Fecha", "Revision.FechaEnvioOtv", "DialogoEncargoCorrectivo.FechaInicio", "DialogoEncargoCorrectivo.FechaFinLimite", "DialogoResultadoCorrectivo.FechaInicioReal", "DialogoResultadoCorrectivo.FechaFinReal", "TrabajoCorrectivo.FechaCreacion", "TrabajoCorrectivo.FechaIncidencia", "TrabajoCorrectivo.FechaModificacion", "Verificar.FechaInicio", "Verificar.FechaFin", "TrabajoCorrectivo.CodigoIncidencia", "Revision.TiempoMedio", "DialogoResultadoCorrectivo.Foto", "TrabajoCorrectivo.Foto", "TrabajoCorrectivo.ImagenMapa", "Verificar.Imagen", "Verificar.FirmaOperario", "TrabajoCorrectivo.Origen", "TrabajoCorrectivo.Prioridad", "TrabajoCorrectivo.TipoIncidencia", "TrabajoCorrectivo.Estado", "Revision.Orden", "Revision.Resultado", "DialogoEncargoCorrectivo.Adjuntos", "DialogoResultadoCorrectivo.Adjuntos", "TrabajoCorrectivo.AdjuntosIncidencia", "DialogoEncargoCorrectivo.Observaciones", "DialogoResultadoCorrectivo.Observaciones", "TrabajoCorrectivo.Descripcion", "Verificar.Observaciones", "TrabajoCorrectivo.CampoActuable"}, true, null, 0, "")).require(_parameter("fields", new String[]{"Position", "Check", "Text", "Section", "Date", "Serial", "Number", "Picture", "Video", "Select", "File", "Memo", "Link"}, true, null, 0, "")).assume(isTerminalInstance(), isFacetInstance()));
		in("Node.View.IsDefault").def(context("Concept").allow(name()).require().assume(isTerminalInstance()));
		in("Collection").def(context("Concept").allow(multiple("Set.Sort"), parameter("mode:word", new String[]{"Table", "List", "Document"}, false, null, 0, ""), parameter("filter", "native", false, null, 1, "Filter#public boolean accept(monet.Entry entry)#Monet"), parameter("select", "native", false, null, 2, "Select#public boolean accept(monet.Entry entry)#Monet"), parameter("historyStore", "string", false, null, 3, "##Monet"), name()).require().assume(isTerminalInstance(), isFacetInstance()));
		in("Dictionary.Term").def(context("Concept").allow(multiple("Dictionary.Term"), parameter("tags", "string", true, null, 1, "##Monet"), parameter("category", "boolean", false, null, 2, "##Monet"), parameter("label", "string", false, null, 0, "##Monet"), name()).require(_parameter("label", "string", false, null, 0, "##Monet"), _name()).assume(isTerminalInstance()));
		in("Dictionary").def(context("Concept").allow(multiple("Dictionary.Term"), multiple("Dictionary.FromRoles"), multiple("Dictionary.FromCollectable"), parameter("onPopulated", "native", false, null, 0, "Event#public void execute()#Monet"), parameter("onSynchronized", "native", false, null, 1, "Event#public void execute()#Monet"), parameter("onTermAdded", "native", false, null, 2, "TermEvent#public void execute(monet.Dictionary.Term term)#Monet"), parameter("onTermModified", "native", false, null, 3, "TermEvent#public void execute(monet.Dictionary.Term term)#Monet"), name()).require().assume(isMain(), isTerminalInstance()));
		in("Dictionary.FromRoles").def(context("Concept").allow(name(), parameter("roles", new String[]{"Role"}, true, null, 0, "")).require(_parameter("roles", new String[]{"Role"}, true, null, 0, "")).assume(isTerminalInstance()));
		in("User").def(context("Concept").allow(parameter("environments", new String[]{"EscritorioCoordinador.[annonymous@IsEnvironment]", "EscritorioAdministradorSistema.[annonymous@IsEnvironment]", "EscritorioInspector.[annonymous@IsEnvironment]", "EscritorioNotificador.[annonymous@IsEnvironment]"}, true, null, 4, ""), name(), parameter("username", "string", false, null, 0, "##Monet"), parameter("name", "string", false, null, 1, "##Monet"), parameter("email", "string", false, null, 2, "##Monet"), parameter("photo", "file", false, null, 3, "[pngjpg]##Monet##Monet")).require(_parameter("username", "string", false, null, 0, "##Monet"), _parameter("name", "string", false, null, 1, "##Monet"), _parameter("email", "string", false, null, 2, "##Monet"), _parameter("photo", "file", false, null, 3, "[pngjpg]##Monet##Monet")).assume(isMain(), isTerminalInstance()));
		in("Form").def(context("Concept").allow(multiple("FieldView.IsDefault"), parameter("layout", "string", false, null, 1, "##Monet"), name(), parameter("fields", new String[]{"DialogoEncargoCorrectivo.Urgente", "TrabajoCorrectivo.Urgente", "Verificar.Verificado", "DialogoResultadoCorrectivo.Responsable", "TrabajoCorrectivo.CreadaPor", "TrabajoCorrectivo.CodigoNotificacionIncidencia", "TrabajoCorrectivo.ObjetoPadre", "TrabajoCorrectivo.RegistroEntrada", "TrabajoCorrectivo.RegistroSalida", "TrabajoCorrectivo.Unidad", "TrabajoCorrectivo.TipoIcc", "Edificio.Equipamiento", "Instalacion.Componente", "Revision.Fecha", "Revision.FechaEnvioOtv", "DialogoEncargoCorrectivo.FechaInicio", "DialogoEncargoCorrectivo.FechaFinLimite", "DialogoResultadoCorrectivo.FechaInicioReal", "DialogoResultadoCorrectivo.FechaFinReal", "TrabajoCorrectivo.FechaCreacion", "TrabajoCorrectivo.FechaIncidencia", "TrabajoCorrectivo.FechaModificacion", "Verificar.FechaInicio", "Verificar.FechaFin", "TrabajoCorrectivo.CodigoIncidencia", "Revision.TiempoMedio", "DialogoResultadoCorrectivo.Foto", "TrabajoCorrectivo.Foto", "TrabajoCorrectivo.ImagenMapa", "Verificar.Imagen", "Verificar.FirmaOperario", "TrabajoCorrectivo.Origen", "TrabajoCorrectivo.Prioridad", "TrabajoCorrectivo.TipoIncidencia", "TrabajoCorrectivo.Estado", "Revision.Orden", "Revision.Resultado", "DialogoEncargoCorrectivo.Adjuntos", "DialogoResultadoCorrectivo.Adjuntos", "TrabajoCorrectivo.AdjuntosIncidencia", "DialogoEncargoCorrectivo.Observaciones", "DialogoResultadoCorrectivo.Observaciones", "TrabajoCorrectivo.Descripcion", "Verificar.Observaciones", "TrabajoCorrectivo.CampoActuable"}, true, null, 0, "")).require(_parameter("fields", new String[]{"Position", "Check", "Text", "Section", "Date", "Serial", "Number", "Picture", "Video", "Select", "File", "Memo", "Link"}, true, null, 0, "")).assume(isTerminalInstance(), isFacetInstance()));
		in("Select.SelectView").def(context("Concept").allow(parameter("refresh", "native", false, null, 0, "Action#public void execute()#Monet"), parameter("flatten:word", new String[]{"None", "All", "Level", "Leaf", "Internal"}, false, null, 1, ""), parameter("depth", "natural", false, null, 2, "##Monet"), parameter("root", "native", false, null, 3, "SourceTerm#public monet.Dictionary.Term load()#Monet"), parameter("filter", "native", false, null, 4, "Filter#public boolean accept(monet.Entry entry)#Monet"), parameter("showKey", "boolean", false, null, 5, "##Monet"), name(), facet("PlaceMap"), facet("Table"), facet("Poll"), facet("Collection"), facet("History"), facet("Catalog")).require().assume(isFeatureInstance(), isTerminalInstance()));
		in("Terminal").def(context("Concept").allow(parameter("mode:word", new String[]{"Terminate", "Abort"}, false, null, 0, ""), name()).require().assume(isFacetInstance(), isTerminalInstance()));
		in("EntityLink").def(context("Concept").allow(name(), parameter("entity", new String[]{"TrabajoPreventivo", "Inventario", "Lugar", "Edificio", "Instalacion", "NotificacionIncidencia", "Trabajos", "Trabajo", "TrabajoCorrectivo", "EscritorioCoordinador", "EscritorioAdministradorSistema", "EscritorioInspector", "EscritorioNotificador", "Suministradores", "Piezas", "Preferencias", "Verificar", "ControlCalidad", "DialogoEncargoCorrectivo.Urgente", "TrabajoCorrectivo.Urgente", "Verificar.Verificado", "DialogoResultadoCorrectivo.Responsable", "TrabajoCorrectivo.CreadaPor", "TrabajoCorrectivo.CodigoNotificacionIncidencia", "TrabajoCorrectivo.ObjetoPadre", "TrabajoCorrectivo.RegistroEntrada", "TrabajoCorrectivo.RegistroSalida", "TrabajoCorrectivo.Unidad", "TrabajoCorrectivo.TipoIcc", "Edificio.Equipamiento", "Instalacion.Componente", "Revision.Fecha", "Revision.FechaEnvioOtv", "DialogoEncargoCorrectivo.FechaInicio", "DialogoEncargoCorrectivo.FechaFinLimite", "DialogoResultadoCorrectivo.FechaInicioReal", "DialogoResultadoCorrectivo.FechaFinReal", "TrabajoCorrectivo.FechaCreacion", "TrabajoCorrectivo.FechaIncidencia", "TrabajoCorrectivo.FechaModificacion", "Verificar.FechaInicio", "Verificar.FechaFin", "TrabajoCorrectivo.CodigoIncidencia", "Revision.TiempoMedio", "Revisando.[annonymous@Workmap].Configura.[annonymous@CreateDialog].DialogoEncargoCorrectivo", "Revisando.[annonymous@Workmap].Cumplimenta.[annonymous@CreateDialog].DialogoResultadoCorrectivo", "DialogoEncargoCorrectivo", "DialogoResultadoCorrectivo", "DialogoResultadoCorrectivo.Foto", "TrabajoCorrectivo.Foto", "TrabajoCorrectivo.ImagenMapa", "Verificar.Imagen", "Verificar.FirmaOperario", "TrabajoCorrectivo.Origen", "TrabajoCorrectivo.Prioridad", "TrabajoCorrectivo.TipoIncidencia", "TrabajoCorrectivo.Estado", "Revision.Orden", "Revision.Resultado", "DialogoEncargoCorrectivo.Adjuntos", "DialogoResultadoCorrectivo.Adjuntos", "TrabajoCorrectivo.AdjuntosIncidencia", "DialogoEncargoCorrectivo.Observaciones", "DialogoResultadoCorrectivo.Observaciones", "TrabajoCorrectivo.Descripcion", "Verificar.Observaciones", "TrabajoCorrectivo.CampoActuable"}, true, null, 0, "")).require(_parameter("entity", new String[]{"Position", "Node", "Check", "Text", "Document", "Section", "Date", "Serial", "Number", "Dialog", "Picture", "Video", "Select", "File", "Memo", "Link"}, true, null, 0, "")).assume(isTerminalInstance(), isFacetInstance()));
		in("PagePreview").def(context("Concept").allow(name()).require().assume(isFacetInstance(), isTerminalInstance()));
		in("Document.View").def(context("Concept").allow(parameter("label", "string", false, null, 0, "##Monet"), parameter("refresh", "native", false, null, 1, "Action#public void execute()#Monet"), name(), facet("PagePreview")).require().assume(isTerminalInstance()));
		in("Poll").def(context("Concept").allow(multiple("FieldView.IsDefault"), name()).require().assume(isTerminalInstance(), isFacetInstance()));
		in("Node.View.HideBreadCrumbs").def(context("Concept").allow(name()).require().assume(isTerminalInstance()));
		in("FollowerList").def(context("Concept").allow(name()).require().assume(isFacetInstance(), isTerminalInstance()));
	}

	@Override
	public String languageName() {
		return "Externa";
	}

	@Override
	public Locale locale() {
		return Locale.ENGLISH;
	}

	@Override
	public boolean isTerminalLanguage() {
		return true;
	}
}
