/* The following code was generated by JFlex 1.4.3 on 8/10/14 8:16 */

package siani.tara.intellij.highlighting;

import com.intellij.lexer.FlexLexer;
import com.intellij.openapi.project.Project;
import com.intellij.psi.TokenType;
import com.intellij.psi.tree.IElementType;
import siani.tara.intellij.lang.TaraLanguage;
import siani.tara.intellij.lang.psi.TaraTypes;
import siani.tara.lang.Model;

import java.util.Set;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 8/10/14 8:16 from the specification file
 * <tt>/Users/oroncal/workspace/tara/intellij/src/siani/tara/intellij/highlighting/TaraHighlighterLex.flex</tt>
 */
class TaraHighlighterLex implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\52\1\56\1\54\3\0\16\52\4\0\1\56\2\0\1\53\1\35"+
    "\1\37\1\51\1\45\1\31\1\32\1\40\1\50\1\41\1\46\1\33"+
    "\1\0\12\55\1\42\1\44\1\0\1\43\1\56\2\0\2\47\1\1"+
	    "\27\47\4\0\1\47\1\0\1\14\1\12\1\4\1\16\1\5\1\30" +
	    "\1\25\1\13\1\17\2\47\1\20\1\27\1\3\1\2\1\6\1\26" +
	    "\1\23\1\10\1\7\1\11\1\24\1\21\1\15\1\22\1\47\1\34" +
	    "\1\0\1\34\1\0\41\52\2\0\4\47\4\0\1\47\2\0\1\52"+
    "\7\0\1\47\4\0\1\47\5\0\27\47\1\0\37\47\1\0\u013f\47"+
    "\31\0\162\47\4\0\14\47\16\0\5\47\11\0\1\47\21\0\130\52"+
    "\5\0\23\52\12\0\1\47\13\0\1\47\1\0\3\47\1\0\1\47"+
    "\1\0\24\47\1\0\54\47\1\0\46\47\1\0\5\47\4\0\202\47"+
    "\1\0\4\52\3\0\105\47\1\0\46\47\2\0\2\47\6\0\20\47"+
    "\41\0\46\47\2\0\1\47\7\0\47\47\11\0\21\52\1\0\27\52"+
    "\1\0\3\52\1\0\1\52\1\0\2\52\1\0\1\52\13\0\33\47"+
    "\5\0\3\47\15\0\4\52\14\0\6\52\13\0\32\47\5\0\13\47"+
    "\16\52\7\0\12\55\4\0\2\47\1\52\143\47\1\0\1\47\10\52"+
    "\1\0\6\52\2\47\2\52\1\0\4\52\2\47\12\55\3\47\2\0"+
    "\1\47\17\0\1\52\1\47\1\52\36\47\33\52\2\0\3\47\60\0"+
    "\46\47\13\52\1\47\u014f\0\3\52\66\47\2\0\1\52\1\47\20\52"+
    "\2\0\1\47\4\52\3\0\12\47\2\52\2\0\12\55\21\0\3\52"+
    "\1\0\10\47\2\0\2\47\2\0\26\47\1\0\7\47\1\0\1\47"+
    "\3\0\4\47\2\0\1\52\1\47\7\52\2\0\2\52\2\0\3\52"+
    "\11\0\1\52\4\0\2\47\1\0\3\47\2\52\2\0\12\55\4\47"+
    "\15\0\3\52\1\0\6\47\4\0\2\47\2\0\26\47\1\0\7\47"+
    "\1\0\2\47\1\0\2\47\1\0\2\47\2\0\1\52\1\0\5\52"+
    "\4\0\2\52\2\0\3\52\13\0\4\47\1\0\1\47\7\0\12\55"+
    "\2\52\3\47\14\0\3\52\1\0\11\47\1\0\3\47\1\0\26\47"+
    "\1\0\7\47\1\0\2\47\1\0\5\47\2\0\1\52\1\47\10\52"+
    "\1\0\3\52\1\0\3\52\2\0\1\47\17\0\2\47\2\52\2\0"+
    "\12\55\1\0\1\47\17\0\3\52\1\0\10\47\2\0\2\47\2\0"+
    "\26\47\1\0\7\47\1\0\2\47\1\0\5\47\2\0\1\52\1\47"+
    "\6\52\3\0\2\52\2\0\3\52\10\0\2\52\4\0\2\47\1\0"+
    "\3\47\4\0\12\55\1\0\1\47\20\0\1\52\1\47\1\0\6\47"+
    "\3\0\3\47\1\0\4\47\3\0\2\47\1\0\1\47\1\0\2\47"+
    "\3\0\2\47\3\0\3\47\3\0\10\47\1\0\3\47\4\0\5\52"+
    "\3\0\3\52\1\0\4\52\11\0\1\52\17\0\11\55\11\0\1\47"+
    "\7\0\3\52\1\0\10\47\1\0\3\47\1\0\27\47\1\0\12\47"+
    "\1\0\5\47\4\0\7\52\1\0\3\52\1\0\4\52\7\0\2\52"+
    "\11\0\2\47\4\0\12\55\22\0\2\52\1\0\10\47\1\0\3\47"+
    "\1\0\27\47\1\0\12\47\1\0\5\47\2\0\1\52\1\47\7\52"+
    "\1\0\3\52\1\0\4\52\7\0\2\52\7\0\1\47\1\0\2\47"+
    "\4\0\12\55\22\0\2\52\1\0\10\47\1\0\3\47\1\0\27\47"+
    "\1\0\20\47\4\0\6\52\2\0\3\52\1\0\4\52\11\0\1\52"+
    "\10\0\2\47\4\0\12\55\22\0\2\52\1\0\22\47\3\0\30\47"+
    "\1\0\11\47\1\0\1\47\2\0\7\47\3\0\1\52\4\0\6\52"+
    "\1\0\1\52\1\0\10\52\22\0\2\52\15\0\60\47\1\52\2\47"+
    "\7\52\4\0\10\47\10\52\1\0\12\55\47\0\2\47\1\0\1\47"+
    "\2\0\2\47\1\0\1\47\2\0\1\47\6\0\4\47\1\0\7\47"+
    "\1\0\3\47\1\0\1\47\1\0\1\47\2\0\2\47\1\0\4\47"+
    "\1\52\2\47\6\52\1\0\2\52\1\47\2\0\5\47\1\0\1\47"+
    "\1\0\6\52\2\0\12\55\2\0\2\47\42\0\1\47\27\0\2\52"+
    "\6\0\12\55\13\0\1\52\1\0\1\52\1\0\1\52\4\0\2\52"+
    "\10\47\1\0\42\47\6\0\24\52\1\0\2\52\4\47\4\0\10\52"+
    "\1\0\44\52\11\0\1\52\71\0\42\47\1\0\5\47\1\0\2\47"+
    "\1\0\7\52\3\0\4\52\6\0\12\55\6\0\6\47\4\52\106\0"+
    "\46\47\12\0\51\47\7\0\132\47\5\0\104\47\5\0\122\47\6\0"+
    "\7\47\1\0\77\47\1\0\1\47\1\0\4\47\2\0\7\47\1\0"+
    "\1\47\1\0\4\47\2\0\47\47\1\0\1\47\1\0\4\47\2\0"+
    "\37\47\1\0\1\47\1\0\4\47\2\0\7\47\1\0\1\47\1\0"+
    "\4\47\2\0\7\47\1\0\7\47\1\0\27\47\1\0\37\47\1\0"+
    "\1\47\1\0\4\47\2\0\7\47\1\0\47\47\1\0\23\47\16\0"+
    "\11\55\56\0\125\47\14\0\u026c\47\2\0\10\47\12\0\32\47\5\0"+
    "\113\47\3\0\3\47\17\0\15\47\1\0\4\47\3\52\13\0\22\47"+
    "\3\52\13\0\22\47\2\52\14\0\15\47\1\0\3\47\1\0\2\52"+
    "\14\0\64\47\40\52\3\0\1\47\3\0\2\47\1\52\2\0\12\55"+
    "\41\0\3\52\2\0\12\55\6\0\130\47\10\0\51\47\1\52\126\0"+
    "\35\47\3\0\14\52\4\0\14\52\12\0\12\55\36\47\2\0\5\47"+
    "\u038b\0\154\47\224\0\234\47\4\0\132\47\6\0\26\47\2\0\6\47"+
    "\2\0\46\47\2\0\6\47\2\0\10\47\1\0\1\47\1\0\1\47"+
    "\1\0\1\47\1\0\37\47\2\0\65\47\1\0\7\47\1\0\1\47"+
    "\3\0\3\47\1\0\7\47\3\0\4\47\2\0\6\47\4\0\15\47"+
    "\5\0\3\47\1\0\7\47\17\0\4\52\32\0\5\52\20\0\2\47"+
    "\23\0\1\47\13\0\4\52\6\0\6\52\1\0\1\47\15\0\1\47"+
    "\40\0\14\47\1\36\5\47\36\0\15\52\4\0\1\52\3\0\6\52"+
    "\27\0\1\47\4\0\1\47\2\0\12\47\1\0\1\47\3\0\5\47"+
    "\6\0\1\47\1\0\1\47\1\0\1\47\1\0\4\47\1\0\3\47"+
    "\1\0\7\47\3\0\3\47\5\0\5\47\26\0\44\47\u0e81\0\3\47"+
    "\31\0\11\47\6\52\1\0\5\47\2\0\5\47\4\0\126\47\2\0"+
    "\2\52\2\0\3\47\1\0\137\47\5\0\50\47\4\0\136\47\21\0"+
    "\30\47\70\0\20\47\u0200\0\u19b6\47\112\0\u51a6\47\132\0\u048d\47\u0773\0"+
    "\u2ba4\47\u215c\0\u012e\47\2\0\73\47\225\0\7\47\14\0\5\47\5\0"+
    "\1\47\1\52\12\47\1\0\15\47\1\0\5\47\1\0\1\47\1\0"+
    "\2\47\1\0\2\47\1\0\154\47\41\0\u016b\47\22\0\100\47\2\0"+
    "\66\47\50\0\15\47\3\0\20\52\20\0\4\52\17\0\2\47\30\0"+
    "\3\47\31\0\1\47\6\0\5\47\1\0\207\47\2\0\1\52\4\0"+
    "\1\47\13\0\12\55\7\0\32\47\4\0\1\47\1\0\32\47\12\0"+
    "\132\47\3\0\6\47\2\0\6\47\2\0\6\47\2\0\3\47\3\0"+
    "\2\47\3\0\2\47\22\0\3\52\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
	  "\1\0\1\1\23\2\1\3\1\4\2\5\1\6\1\7" +
		  "\1\10\1\11\1\12\1\13\1\14\1\15\5\1\1\16"+
		  "\1\17\1\16\1\2\1\20\17\2\1\21\4\2\1\22" +
		  "\5\2\2\0\1\23\1\0\1\24\1\25\1\0\1\26"+
		  "\2\0\15\2\1\27\2\2\1\30\1\2\1\31\1\32" +
		  "\10\2\1\15\2\2\1\33\2\0\1\34\1\0\1\35" +
		  "\7\2\1\36\3\2\1\37\6\2\1\40\1\2\1\41" +
		  "\1\42\3\2\1\0\1\43\1\0\2\2\1\44\3\2" +
		  "\1\45\15\2\1\46\1\43\2\0\10\2\1\47\1\50" +
		  "\2\2\1\51\1\52\4\2\1\0\1\53\1\54\2\2" +
		  "\1\55\1\2\1\56\2\2\1\57\1\2\1\60\2\2" +
		  "\1\61\2\2\1\62\1\63\2\2\1\64\1\65\1\2" +
		  "\1\66\1\67\1\70\1\71";

  private static int [] zzUnpackAction() {
	  int[] result = new int[215];
	  int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\274\0\353\0\u011a\0\u0149"+
    "\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292\0\u02c1"+
	    "\0\u02f0\0\u031f\0\u034e\0\u037d\0\u03ac\0\57\0\57\0\u03db" +
	    "\0\57\0\u0292\0\u0292\0\57\0\57\0\57\0\57\0\57" +
	    "\0\57\0\u040a\0\u0439\0\u0468\0\u0497\0\u04c6\0\u04f5\0\u0524" +
	    "\0\u0553\0\u0582\0\u0292\0\u05b1\0\u05e0\0\u060f\0\u063e\0\u066d" +
	    "\0\u069c\0\u06cb\0\u06fa\0\u0729\0\u0758\0\u0787\0\u07b6\0\u07e5" +
	    "\0\u0814\0\u0843\0\u0292\0\u0872\0\u08a1\0\u08d0\0\u08ff\0\u0292" +
	    "\0\u092e\0\u095d\0\u098c\0\u09bb\0\u09ea\0\u0a19\0\u040a\0\57" +
	    "\0\u0a48\0\u0a77\0\u0497\0\u04c6\0\57\0\u0aa6\0\u0ad5\0\u0b04" +
	    "\0\u0b33\0\u0b62\0\u0b91\0\u0bc0\0\u0bef\0\u0c1e\0\u0c4d\0\u0c7c"+
	    "\0\u0cab\0\u0cda\0\u0d09\0\u0d38\0\u0292\0\u0d67\0\u0d96\0\u0292" +
	    "\0\u0dc5\0\u0292\0\u0292\0\u0df4\0\u0e23\0\u0e52\0\u0e81\0\u0eb0" +
	    "\0\u0edf\0\u0f0e\0\u0f3d\0\u0292\0\u0f6c\0\u0f9b\0\57\0\u0fca" +
	    "\0\u0ff9\0\u1028\0\u1057\0\u1086\0\u10b5\0\u10e4\0\u1113\0\u1142"+
	    "\0\u1171\0\u11a0\0\u11cf\0\u0292\0\u11fe\0\u122d\0\u125c\0\u0292" +
	    "\0\u128b\0\u12ba\0\u12e9\0\u1318\0\u1347\0\u1376\0\u0292\0\u13a5" +
	    "\0\u0292\0\u0292\0\u13d4\0\u1403\0\u1432\0\u1461\0\u0ff9\0\u1490" +
	    "\0\u14bf\0\u14ee\0\u0292\0\u151d\0\u154c\0\u157b\0\u0292\0\u15aa" +
	    "\0\u15d9\0\u1608\0\u1637\0\u1666\0\u1695\0\u16c4\0\u16f3\0\u1722"+
	    "\0\u1751\0\u1780\0\u17af\0\u17de\0\u0292\0\u180d\0\u183c\0\u186b" +
	    "\0\u189a\0\u18c9\0\u18f8\0\u1927\0\u1956\0\u1985\0\u19b4\0\u19e3"+
	    "\0\u0292\0\u0292\0\u1a12\0\u1a41\0\u0292\0\u0292\0\u1a70\0\u1a9f" +
	    "\0\u1ace\0\u1afd\0\u1b2c\0\u0292\0\u0292\0\u1b5b\0\u1b8a\0\u0292" +
	    "\0\u1bb9\0\u0292\0\u1be8\0\u1c17\0\u0292\0\u1c46\0\u0292\0\u1c75" +
	    "\0\u1ca4\0\u1cd3\0\u1d02\0\u1d31\0\u0292\0\u0292\0\u1d60\0\u1d8f" +
	    "\0\u0292\0\u0292\0\u1dbe\0\u0292\0\u0292\0\u0292\0\u0292";

  private static int [] zzUnpackRowMap() {
	  int[] result = new int[215];
	  int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
	    "\1\17\1\22\1\17\1\23\1\24\3\17\1\25\1\26" +
	    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
	    "\1\37\1\40\1\41\1\42\1\43\1\17\1\44\1\45" +
	    "\1\2\1\46\1\47\1\50\1\51\60\0\1\17\1\52" +
	    "\26\17\4\0\2\17\7\0\2\17\2\0\1\17\2\0" +
	    "\1\17\2\0\2\17\1\53\25\17\4\0\2\17\7\0" +
	    "\2\17\2\0\1\17\2\0\1\17\2\0\13\17\1\54" +
	    "\14\17\4\0\2\17\7\0\2\17\2\0\1\17\2\0" +
	    "\1\17\2\0\1\17\1\55\26\17\4\0\2\17\7\0" +
	    "\2\17\2\0\1\17\2\0\1\17\2\0\14\17\1\56" +
	    "\11\17\1\57\1\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\1\17\1\60\20\17\1\61" +
	    "\5\17\4\0\2\17\7\0\2\17\2\0\1\17\2\0" +
	    "\1\17\2\0\4\17\1\62\15\17\1\63\5\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\6\17\1\64\1\17\1\65\5\17\1\66\11\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\2\17\1\67\4\17\1\70\20\17\4\0\2\17\7\0" +
	    "\2\17\2\0\1\17\2\0\1\17\2\0\1\17\1\71" +
	    "\26\17\4\0\2\17\7\0\2\17\2\0\1\17\2\0" +
	    "\1\17\2\0\13\17\1\72\14\17\4\0\2\17\7\0" +
	    "\2\17\2\0\1\17\2\0\1\17\2\0\7\17\1\73" +
	    "\7\17\1\74\10\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\30\17\4\0\2\17\7\0" +
	    "\2\17\2\0\1\17\2\0\1\17\2\0\1\17\1\75" +
	    "\11\17\1\76\14\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\2\17\1\77\4\17\1\100" +
	    "\20\17\4\0\2\17\7\0\2\17\2\0\1\17\2\0" +
	    "\1\17\2\0\1\17\1\101\14\17\1\102\11\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\4\17\1\103\23\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\13\17\1\104\14\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\13\17\1\105\14\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\34\0\1\106\23\0\45\107\1\110" +
	    "\11\107\46\0\1\111\6\0\1\112\56\0\1\50\2\0" +
	    "\30\113\4\0\2\113\10\0\1\113\2\0\1\113\2\0" +
	    "\1\113\1\0\54\114\1\115\2\114\54\0\1\47\35\0" +
	    "\1\116\12\0\1\117\6\0\1\50\57\0\1\51\1\0" +
	    "\2\17\1\120\25\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\6\17\1\121\17\17\1\122" +
	    "\1\17\4\0\2\17\7\0\2\17\2\0\1\17\2\0" +
	    "\1\17\2\0\1\17\1\123\24\17\1\124\1\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\6\17\1\125\21\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\5\17\1\126\22\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\22\17\1\127\5\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\1\17\1\130\14\17\1\131" +
	    "\11\17\4\0\2\17\7\0\2\17\2\0\1\17\2\0" +
	    "\1\17\2\0\22\17\1\132\5\17\4\0\2\17\7\0" +
	    "\2\17\2\0\1\17\2\0\1\17\2\0\10\17\1\133" +
	    "\17\17\4\0\2\17\7\0\2\17\2\0\1\17\2\0" +
	    "\1\17\2\0\22\17\1\134\5\17\4\0\2\17\7\0" +
	    "\2\17\2\0\1\17\2\0\1\17\2\0\11\17\1\135" +
	    "\16\17\4\0\2\17\7\0\2\17\2\0\1\17\2\0" +
	    "\1\17\2\0\2\17\1\136\25\17\4\0\2\17\7\0" +
	    "\2\17\2\0\1\17\2\0\1\17\2\0\16\17\1\137" +
	    "\11\17\4\0\2\17\7\0\2\17\2\0\1\17\2\0" +
	    "\1\17\2\0\4\17\1\140\23\17\4\0\2\17\7\0" +
	    "\2\17\2\0\1\17\2\0\1\17\2\0\1\17\1\141" +
	    "\12\17\1\142\13\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\7\17\1\143\20\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\20\17\1\144\7\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\10\17\1\145\17\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\6\17\1\146\21\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\6\17\1\147\21\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\22\17\1\150\5\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\6\17\1\151\21\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\7\17\1\152\15\17\1\153\2\17\4\0\2\17\7\0" +
	    "\2\17\2\0\1\17\2\0\1\17\2\0\22\17\1\154" +
	    "\5\17\4\0\2\17\7\0\2\17\2\0\1\17\2\0" +
	    "\1\17\2\0\3\17\1\155\13\17\1\156\10\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\34\0" +
	    "\1\157\23\0\46\160\1\161\10\160\33\0\1\116\21\0" +
	    "\1\112\56\0\1\162\51\0\1\163\4\0\1\164\2\0" +
	    "\3\17\1\165\24\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\10\17\1\166\17\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\4\17\1\167\23\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\22\17\1\170\5\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\5\17\1\171\22\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\4\17\1\172\23\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\6\17\1\173\21\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\6\17\1\174\21\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\5\17\1\175\22\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\23\17\1\176\4\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\26\17\1\177\1\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\4\17\1\200\23\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\16\17\1\201\11\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\24\17\1\202\3\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\23\17\1\203\4\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\17\17\1\204\10\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\13\17\1\205\14\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\11\17\1\206\16\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\4\17\1\207\23\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\4\17\1\210\23\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\15\17\1\211\12\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\12\17\1\212\15\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\1\17\1\213\26\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\10\17\1\214\17\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\4\17\1\215\23\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\7\17\1\133\20\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\1\0" +
	    "\46\160\1\216\56\160\1\217\10\160\46\0\1\220\6\0" +
	    "\1\162\56\0\1\164\47\0\1\117\6\0\1\164\2\0" +
	    "\4\17\1\221\23\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\22\17\1\222\5\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\15\17\1\223\12\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\15\17\1\224\12\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\1\17\1\225\26\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\2\17\1\226\25\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\21\17\1\227\6\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\4\17\1\230\23\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\13\17\1\231\14\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\16\17\1\232\11\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\2\17\1\233\25\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\17\17\1\234\10\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\4\17\1\235\23\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\4\17\1\236\23\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\21\17\1\237\6\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\17\17\1\240\10\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\2\17\1\241\21\17\1\242\3\17\4\0\2\17\7\0" +
	    "\2\17\2\0\1\17\2\0\1\17\2\0\10\17\1\243" +
	    "\17\17\4\0\2\17\7\0\2\17\2\0\1\17\2\0" +
	    "\1\17\2\0\16\17\1\244\11\17\4\0\2\17\7\0" +
	    "\2\17\2\0\1\17\2\0\1\17\2\0\6\17\1\245" +
	    "\21\17\4\0\2\17\7\0\2\17\2\0\1\17\2\0" +
	    "\1\17\1\0\46\160\1\246\10\160\46\0\1\247\1\0" +
	    "\1\247\4\0\1\250\2\0\5\17\1\251\22\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\13\17\1\252\14\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\16\17\1\253\11\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\2\17\1\254\25\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\15\17\1\255\12\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\22\17\1\256\5\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\6\17\1\257\21\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\2\17\1\260\25\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\24\17\1\261\3\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\4\17\1\262\23\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\22\17\1\263\5\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\13\17\1\264\14\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\7\17\1\265\20\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\4\17\1\266\23\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\6\17\1\267\21\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\4\17\1\270\23\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\22\17\1\271\5\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\22\17\1\272\5\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\47\0\1\246\65\0\1\250\34\0" +
	    "\1\273\21\0\1\250\2\0\6\17\1\274\21\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\17\17\1\275\10\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\2\17\1\276\25\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\4\17\1\277\23\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\7\17\1\300\20\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\6\17\1\301\21\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\4\17\1\302\23\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\13\17\1\303\14\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\7\17\1\304\20\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\2\17\1\305\25\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\16\17\1\306\11\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\22\17\1\307\5\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\2\0\3\17\1\310\24\17\4\0" +
	    "\2\17\7\0\2\17\2\0\1\17\2\0\1\17\2\0" +
	    "\4\17\1\311\23\17\4\0\2\17\7\0\2\17\2\0" +
	    "\1\17\2\0\1\17\56\0\1\312\2\0\13\17\1\313" +
	    "\14\17\4\0\2\17\7\0\2\17\2\0\1\17\2\0" +
	    "\1\17\2\0\2\17\1\314\25\17\4\0\2\17\7\0" +
	    "\2\17\2\0\1\17\2\0\1\17\2\0\21\17\1\315" +
	    "\6\17\4\0\2\17\7\0\2\17\2\0\1\17\2\0" +
	    "\1\17\2\0\17\17\1\316\10\17\4\0\2\17\7\0" +
	    "\2\17\2\0\1\17\2\0\1\17\2\0\13\17\1\317" +
	    "\14\17\4\0\2\17\7\0\2\17\2\0\1\17\2\0" +
	    "\1\17\2\0\1\17\1\320\26\17\4\0\2\17\7\0" +
	    "\2\17\2\0\1\17\2\0\1\17\2\0\4\17\1\321" +
	    "\23\17\4\0\2\17\7\0\2\17\2\0\1\17\2\0" +
	    "\1\17\2\0\15\17\1\322\12\17\4\0\2\17\7\0" +
	    "\2\17\2\0\1\17\2\0\1\17\47\0\1\220\6\0" +
	    "\1\312\2\0\6\17\1\323\21\17\4\0\2\17\7\0" +
	    "\2\17\2\0\1\17\2\0\1\17\2\0\6\17\1\324" +
	    "\21\17\4\0\2\17\7\0\2\17\2\0\1\17\2\0" +
	    "\1\17\2\0\17\17\1\325\10\17\4\0\2\17\7\0" +
	    "\2\17\2\0\1\17\2\0\1\17\2\0\2\17\1\326" +
	    "\25\17\4\0\2\17\7\0\2\17\2\0\1\17\2\0" +
	    "\1\17\2\0\4\17\1\327\23\17\4\0\2\17\7\0" +
	    "\2\17\2\0\1\17\2\0\1\17\1\0";

  private static int [] zzUnpackTrans() {
	  int[] result = new int[7661];
	  int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
	  "\1\0\1\11\23\1\2\11\1\1\1\11\2\1\6\11" +
		  "\44\1\2\0\1\11\1\0\2\1\1\0\1\11\2\0"+
    "\37\1\1\11\2\0\1\1\1\0\32\1\1\0\1\1"+
    "\1\0\26\1\2\0\22\1\1\0\34\1";

  private static int [] zzUnpackAttribute() {
	  int[] result = new int[215];
	  int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
	private Set<String> identifiers;
	private Project project;

	public TaraHighlighterLex(java.io.Reader reader, Project project) {
		this.zzReader = reader;
		this.project = project;
	}

	private IElementType evaluateIdentifier() {
		String identifier = yytext().toString();
		if (identifiers == null) return TaraTypes.IDENTIFIER_KEY;
		return identifiers.contains(identifier) ? TaraTypes.METAIDENTIFIER_KEY : TaraTypes.IDENTIFIER_KEY;
	}

	private void loadHeritage() {
		String[] uses = zzBuffer.toString().split("use");
        String destiny = null;
        for (String use : uses)
            if (use.contains("as metamodel")) {
                destiny = use.split("as metamodel")[0].trim();
                break;
            }
        Model heritage = TaraLanguage.getMetaModel(destiny, project);
        if (heritage != null)
            identifiers = heritage.getIdentifiers();
}


  TaraHighlighterLex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  TaraHighlighterLex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1752) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = (zzBufferArrayL != null ? zzBufferArrayL[zzCurrentPosL++] : zzBufferL.charAt(zzCurrentPosL++));
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 35: 
          { return TaraTypes.STRING_MULTILINE_VALUE_KEY;
          }
        case 58: break;
        case 34: 
          { return TaraTypes.WITH;
          }
        case 59: break;
        case 13: 
          { return TaraTypes.VAR;
          }
        case 60: break;
        case 11: 
          { return TaraTypes.COLON;
          }
        case 61: break;
        case 8: 
          { return TaraTypes.PERCENTAGE;
          }
        case 62: break;
	      case 40: { return TaraTypes.SINGLE;
          }
        case 63: break;
        case 21: 
          { return TaraTypes.CODE_VALUE_KEY;
          }
        case 64: break;
        case 54: 
          { return TaraTypes.COMPONENT;
          }
        case 65: break;
        case 28: 
          { return TaraTypes.DOUBLE_VALUE_KEY;
          }
        case 66: break;
        case 14: 
          { return TokenType.WHITE_SPACE;
          }
        case 67: break;
        case 44: 
          { return TaraTypes.NATURAL_TYPE;
          }
        case 68: break;
        case 4: 
          { return TaraTypes.RIGHT_PARENTHESIS;
          }
        case 69: break;
        case 27: 
          { return TaraTypes.LIST;
          }
        case 70: break;
        case 12: 
          { return TaraTypes.EQUALS;
          }
        case 71: break;
        case 5: 
          { return TaraTypes.DOT;
          }
        case 72: break;
	      case 39: { return TaraTypes.STRING_TYPE;
          }
        case 73: break;
        case 36: 
          { return TaraTypes.NAMED;
          }
        case 74: break;
        case 51: 
          { return TaraTypes.TERMINAL;
          }
        case 75: break;
        case 32: 
          { return TaraTypes.DATE_TYPE;
          }
        case 76: break;
        case 37: 
          { return TaraTypes.EMPTY_REF;
          }
	      case 77:
		      break;
	      case 3:
          { return TaraTypes.LEFT_PARENTHESIS;
          }
	      case 78:
		      break;
	      case 53:
          { return TaraTypes.REQUIRED;
          }
	      case 79:
		      break;
	      case 46:
          { return TaraTypes.PRIVATE;
          }
	      case 80:
		      break;
	      case 20:
          { return TaraTypes.NEGATIVE_VALUE_KEY;
          }
	      case 81:
		      break;
	      case 22:
          { return TaraTypes.DOC_LINE;
          }
	      case 82:
		      break;
	      case 45:
          { return TaraTypes.EXTENDS;
          }
	      case 83:
		      break;
	      case 19:
          { return TaraTypes.STRING_VALUE_KEY;
          }
	      case 84:
		      break;
	      case 50:
          { return TaraTypes.PROPERTY;
          }
	      case 85:
		      break;
	      case 2:
          { return evaluateIdentifier();
          }
	      case 86:
		      break;
	      case 9:
          { return TaraTypes.STAR;
          }
	      case 87:
		      break;
	      case 42:
          { return TaraTypes.DOUBLE_TYPE;
          }
	      case 88:
		      break;
	      case 15:
          { return TaraTypes.NATURAL_VALUE_KEY;
          }
	      case 89:
		      break;
	      case 49:
          { return TaraTypes.COORDINATE_VALUE_KEY;
          }
	      case 90:
		      break;
	      case 1:
          { return TokenType.BAD_CHARACTER;
          }
	      case 91:
		      break;
	      case 52:
          { return TaraTypes.RESOURCE_KEY;
          }
	      case 92:
		      break;
	      case 24:
          { return TaraTypes.USE_KEY;
          }
	      case 93:
		      break;
	      case 41:
          { return TaraTypes.ALWAYS;
          }
	      case 94:
		      break;
	      case 31:
          { return TaraTypes.BOOLEAN_VALUE_KEY;
          }
	      case 95:
		      break;
	      case 17:
          { return TaraTypes.AS;
          }
	      case 96:
		      break;
	      case 16:
          { return TaraTypes.ON;
          }
	      case 97:
		      break;
	      case 23:
          { return TaraTypes.SUB;
          }
	      case 98:
		      break;
	      case 47:
          { return TaraTypes.BOOLEAN_TYPE;
          }
	      case 99:
		      break;
	      case 18:
          { return TaraTypes.IS;
          }
	      case 100:
		      break;
	      case 30:
          { return TaraTypes.PORT_TYPE;
          }
	      case 101:
		      break;
	      case 48:
          { return TaraTypes.INT_TYPE;
          }
	      case 102:
		      break;
	      case 43:
          { return TaraTypes.METAIDENTIFIER_KEY;
          }
	      case 103:
		      break;
	      case 29:
          { return TaraTypes.DATE_VALUE_KEY;
          }
	      case 104:
		      break;
	      case 57:
          { return TaraTypes.COORDINATE_TYPE;
          }
	      case 105:
		      break;
	      case 55: {
		      return TaraTypes.UNIVERSAL;
          }
        case 106: break;
        case 7: 
          { return TaraTypes.EURO;
          }
        case 107: break;
        case 25: 
          { loadHeritage();
										return TaraTypes.BOX_KEY;
          }
        case 108: break;
        case 33: 
          { return TaraTypes.WORD_KEY;
          }
        case 109: break;
        case 56: 
          { return TaraTypes.INTENTION;
          }
        case 110: break;
        case 6: 
          { return TaraTypes.DOLLAR;
          }
        case 111: break;
        case 38: 
          { return TaraTypes.FACET;
          }
        case 112: break;
        case 10: 
          { return TaraTypes.COMMA;
          }
        case 113: break;
        case 26: 
          { return TaraTypes.HAS;
          }
        case 114: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
