package io.intino.tara.compiler.codegeneration.magritte.layer.templates.layer;

import io.intino.itrules.RuleSet;
import io.intino.itrules.Template;

public class ConstructorTemplate extends Template {

	public RuleSet ruleSet() {
		return new RuleSet().add(
				rule().condition((allTypes("variable", "multiple", "word")), (type("owner")), not(type("inherited")), (attribute("words")), (trigger("constructor"))).output(literal("_load(\"")).output(mark("name", "FirstLowerCase")).output(literal("\", new java.util.ArrayList<>(java.util.Arrays.asList(")).output(mark("wordValues", "quoted").multiple(", ")).output(literal(")));")),
				rule().condition((allTypes("variable", "word")), (type("owner")), not(anyTypes("inherited", "empty")), (attribute("values")), (trigger("constructor"))).output(literal("_load(\"")).output(mark("name", "FirstLowerCase")).output(literal("\", new java.util.ArrayList<>(java.util.Arrays.asList(")).output(mark("wordValues", "quoted").multiple(", ")).output(literal(")));")),
				rule().condition((allTypes("reactive", "variable")), (type("owner")), not(anyTypes("inherited", "empty")), (trigger("constructor"))).output(literal("_load(\"")).output(mark("name", "FirstLowerCase")).output(literal("\", new java.util.ArrayList<>(java.util.Collections.singletonList(")).output(mark("workingPackage")).output(literal(".natives.")).output(mark("package")).output(literal(".")).output(mark("name", "javaValidName")).output(literal("_")).output(mark("uid")).output(literal(".class.getName())));")),
				rule().condition((allTypes("function", "variable")), (type("owner")), not(anyTypes("inherited", "empty")), (attribute("body")), (trigger("constructor"))).output(literal("_load(\"")).output(mark("name", "FirstLowerCase")).output(literal("\", new java.util.ArrayList<>(java.util.Collections.singletonList(")).output(mark("workingPackage")).output(literal(".natives.")).output(mark("package")).output(literal(".")).output(mark("name", "javaValidName")).output(literal("_")).output(mark("uid")).output(literal(".class.getName())));")),
				rule().condition((allTypes("date", "variable")), (type("owner")), not(anyTypes("inherited", "empty")), (attribute("values")), (trigger("constructor"))).output(literal("_load(\"")).output(mark("name", "FirstLowerCase")).output(literal("\", new java.util.ArrayList<>(java.util.Arrays.asList(")).output(mark("values", "quoted").multiple(", ")).output(literal(")));")),
				rule().condition((allTypes("variable", "time")), (type("owner")), not(anyTypes("inherited", "empty")), (attribute("values")), not(type("multiple")), (trigger("constructor"))).output(literal("_load(\"")).output(mark("name", "FirstLowerCase")).output(literal("\",  new java.util.ArrayList<>(java.util.Arrays.asList(")).output(mark("values", "quoted").multiple(", ")).output(literal(")));")),
				rule().condition((allTypes("double", "variable", "multiple")), (type("owner")), not(anyTypes("inherited", "empty")), (attribute("values")), (trigger("constructor"))).output(literal("_load(\"")).output(mark("name", "FirstLowerCase")).output(literal("\", new java.util.ArrayList<>(java.util.Arrays.asList(new Double[] {")).output(mark("values").multiple(", ")).output(literal("})));")),
				rule().condition((allTypes("double", "variable")), (type("owner")), not(anyTypes("inherited", "empty")), (attribute("values")), (trigger("constructor"))).output(literal("_load(\"")).output(mark("name", "FirstLowerCase")).output(literal("\", new java.util.ArrayList<>(java.util.Collections.singletonList((double) ")).output(mark("values")).output(literal(")));")),
				rule().condition((allTypes("reference", "variable")), (type("owner")), not(anyTypes("inherited", "empty")), (attribute("values")), (type("multiple")), (trigger("constructor"))).output(literal("_load(\"")).output(mark("name", "FirstLowerCase")).output(literal("\", new java.util.ArrayList<>(java.util.Arrays.asList(graph().concept(\"")).output(mark("type")).output(literal("\"))));")),
				rule().condition((allTypes("resource", "variable")), (type("owner")), not(anyTypes("inherited", "empty")), (attribute("values")), (trigger("constructor"))).output(literal("_load(\"")).output(mark("name", "FirstLowerCase")).output(literal("\", io.intino.tara.magritte.loaders.StringLoader.load(Arrays.asList(")).output(mark("values", "quoted").multiple(", ")).output(literal(")));")),
				rule().condition((allTypes("owner", "variable")), not(anyTypes("inherited", "empty")), (attribute("values")), (trigger("constructor"))).output(literal("_load(\"")).output(mark("name", "FirstLowerCase")).output(literal("\", new java.util.ArrayList<>(java.util.Arrays.asList(")).output(mark("values").multiple(", ")).output(literal(")));"))
		);
	}
}