package io.intino.tara.compiler.codegeneration.magritte.layer.templates.layer;

import io.intino.itrules.RuleSet;
import io.intino.itrules.Template;

public class DeclarationTemplate extends Template {

	public RuleSet ruleSet() {
		return new RuleSet().add(
				rule().condition((allTypes("owner", "reactive", "variable", "multiple", "word")), not(anyTypes("outdefined", "inherited")), (trigger("declaration"))).output(literal("protected io.intino.tara.magritte.Expression<java.util.List<")).output(mark("type", "FirstUpperCase")).output(literal(">> ")).output(mark("name", "javaValidName")).output(literal(";\n\npublic enum ")).output(mark("name", "FirstUpperCase", "javaValidName")).output(literal(" {\n\t")).output(mark("words").multiple(", ")).output(literal(";\n}")),
				rule().condition((allTypes("owner", "variable", "multiple", "word")), not(anyTypes("outdefined", "inherited")), (trigger("declaration"))).output(literal("protected java.util.List<")).output(mark("type", "FirstUpperCase")).output(literal("> ")).output(mark("name", "FirstLowerCase", "javaValidName")).output(literal(" = new java.util.ArrayList<>();\n\npublic enum ")).output(mark("name", "FirstUpperCase", "javaValidName")).output(literal(" {\n\t")).output(mark("words").multiple(", ")).output(literal(";\n}")),
				rule().condition((allTypes("owner", "outdefined", "variable", "multiple", "word")), not(type("inherited")), (trigger("declaration"))).output(literal("protected java.util.List<")).output(mark("workingPackage", "LowerCase")).output(literal(".rules.")).output(mark("rule", "externalWordClass")).output(literal("> ")).output(mark("name", "FirstLowerCase", "javaValidName")).output(literal(" = new java.util.ArrayList<>();")),
				rule().condition((allTypes("owner", "outdefined", "variable", "word")), not(type("inherited")), (trigger("declaration"))).output(literal("protected ")).output(mark("workingPackage", "LowerCase")).output(literal(".rules.")).output(mark("rule", "externalWordClass")).output(literal(" ")).output(mark("name", "FirstLowerCase", "javaValidName")).output(literal(";")),
				rule().condition((allTypes("owner", "reactive", "variable", "word")), not(anyTypes("outdefined", "inherited")), (trigger("declaration"))).output(literal("protected io.intino.tara.magritte.Expression<")).output(mark("type", "FirstUpperCase")).output(literal("> ")).output(mark("name", "FirstLowerCase", "javaValidName")).output(literal(";\n\npublic enum ")).output(mark("name", "FirstUpperCase", "javaValidName")).output(literal(" {\n\t")).output(mark("words").multiple(", ")).output(literal(";\n}")),
				rule().condition((allTypes("owner", "variable", "word")), not(anyTypes("outdefined", "inherited")), (trigger("declaration"))).output(literal("protected ")).output(mark("type", "FirstUpperCase")).output(literal(" ")).output(mark("name", "FirstLowerCase", "javaValidName")).output(literal(";\n\npublic enum ")).output(mark("name", "FirstUpperCase", "javaValidName")).output(literal(" {\n\t")).output(mark("words").multiple(", ")).output(literal(";\n}")),
				rule().condition((allTypes("owner", "concept", "variable", "multiple")), not(type("inherited")), not(type("overriden")), (trigger("declaration"))).output(literal("protected java.util.List<io.intino.tara.magritte.Concept> ")).output(mark("name", "FirstLowerCase", "javaValidName")).output(literal(" = new java.util.ArrayList<>();")),
				rule().condition((allTypes("owner", "reactive", "variable", "multiple")), not(type("inherited")), not(type("overriden")), (trigger("declaration"))).output(literal("protected io.intino.tara.magritte.Expression<java.util.List<")).output(mark("type", "fullType", "reference")).output(literal(">> ")).output(mark("name", "FirstLowerCase", "javaValidName")).output(literal(";")),
				rule().condition((allTypes("owner", "reactive", "concept", "variable")), not(type("inherited")), not(type("multiple")), not(type("overriden")), (trigger("declaration"))).output(literal("protected io.intino.tara.magritte.Expression<io.intino.tara.magritte.Concept> ")).output(mark("name", "FirstLowerCase", "javaValidName")).output(literal(";")),
				rule().condition((allTypes("owner", "reactive", "variable")), not(type("inherited")), not(type("multiple")), not(type("overriden")), (trigger("declaration"))).output(literal("protected io.intino.tara.magritte.Expression<")).output(mark("type", "fullType", "reference")).output(literal("> ")).output(mark("name", "FirstLowerCase", "javaValidName")).output(literal(";")),
				rule().condition((allTypes("function", "variable")), (type("owner")), not(type("inherited")), not(type("overriden")), (trigger("declaration"))).output(literal("protected ")).output(mark("workingPackage", "LowerCase")).output(literal(".functions.")).output(mark("rule", "interfaceClass")).output(literal(" ")).output(mark("name", "FirstLowerCase", "javaValidName")).output(literal(";")),
				rule().condition((allTypes("owner", "variable")), not(type("concept")), (type("multiple")), not(type("inherited")), not(type("overriden")), (trigger("declaration"))).output(literal("protected java.util.List<")).output(mark("type", "fullType", "reference")).output(literal("> ")).output(mark("name", "FirstLowerCase", "javaValidName")).output(literal(" = new java.util.ArrayList<>();")),
				rule().condition((allTypes("owner", "variable")), not(type("concept")), not(type("multiple")), not(type("inherited")), not(type("overriden")), (trigger("declaration"))).output(literal("protected ")).output(mark("type", "reference", "variableType")).output(literal(" ")).output(mark("name", "FirstLowerCase", "javaValidName")).output(literal(";")),
				rule().condition((type("facettarget")), not(type("overriden")), (trigger("declaration"))).output(literal("protected ")).output(mark("qn", "reference")).output(literal(" _")).output(mark("name", "javaValidName", "FirstLowerCase")).output(literal(";")),
				rule().condition((type("constraint")), (trigger("declaration"))).output(literal("protected ")).output(mark("qn", "reference")).output(literal(" _")).output(mark("name", "javaValidName", "FirstLowerCase")).output(literal(";")),
				rule().condition((allTypes("owner", "variable")), (type("concept")), not(anyTypes("instance", "inherited", "multiple", "overriden")), (trigger("declaration"))).output(literal("protected io.intino.tara.magritte.Concept ")).output(mark("name", "FirstLowerCase", "javaValidName")).output(literal(";")),
				rule().condition((allTypes("owner", "single", "node")), not(anyTypes("instance", "inherited", "overriden")), (trigger("declaration"))).output(literal("protected ")).output(mark("qn", "reference")).output(literal(" ")).output(mark("name", "FirstLowerCase", "javaValidName")).output(literal(";")),
				rule().condition((allTypes("owner", "node")), not(anyTypes("single", "instance", "inherited", "overriden")), (trigger("declaration"))).output(literal("protected java.util.List<")).output(mark("qn", "reference")).output(literal("> ")).output(mark("name", "javaValidName", "FirstLowerCase")).output(literal("List = new java.util.ArrayList<>();")),
				rule().condition((type("node")), (trigger("declaration")))
		);
	}
}