package io.intino.tara.compiler.codegeneration.magritte.layer.templates.layer;

import io.intino.itrules.RuleSet;
import io.intino.itrules.Template;

public class SetTemplate extends Template {

	public RuleSet ruleSet() {
		return new RuleSet().add(
				rule().condition((allTypes("facettarget", "overriden")), (trigger("set"))).output(literal("_")).output(mark("name", "FirstLowerCase")).output(literal(".core$().set(_")).output(mark("name", "FirstLowerCase")).output(literal(", name, values);")),
				rule().condition((allTypes("owner", "outdefined", "variable", "multiple", "word")), not(anyTypes("reactive", "inherited", "overriden")), (trigger("set"))).output(literal("if (name.equalsIgnoreCase(\"")).output(mark("name")).output(literal("\")) this.")).output(mark("name", "javaValidName", "FirstLowerCase")).output(literal(" = new java.util.ArrayList<>((java.util.List<")).output(mark("workingPackage", "LowerCase")).output(literal(".rules.")).output(mark("rule", "externalWordClass")).output(literal(">) values);")),
				rule().condition((allTypes("owner", "variable", "multiple", "word")), not(anyTypes("reactive", "inherited", "overriden")), (trigger("set"))).output(literal("if (name.equalsIgnoreCase(\"")).output(mark("name")).output(literal("\")) this.")).output(mark("name", "javaValidName", "FirstLowerCase")).output(literal(" = new java.util.ArrayList<>((java.util.List<")).output(mark("type")).output(literal(">) values);")),
				rule().condition((allTypes("variable", "word")), (type("outdefined")), not(anyTypes("reactive", "inherited", "overriden")), (type("owner")), (trigger("set"))).output(literal("if (name.equalsIgnoreCase(\"")).output(mark("name", "FirstLowerCase")).output(literal("\")) this.")).output(mark("name", "javaValidName", "FirstLowerCase", "javaValidWord")).output(literal(" = (")).output(mark("workingPackage", "LowerCase")).output(literal(".rules.")).output(mark("rule", "externalWordClass")).output(literal(") values.get(0);")),
				rule().condition((allTypes("owner", "variable", "word")), not(anyTypes("reactive", "inherited", "overriden")), (trigger("set"))).output(literal("if (name.equalsIgnoreCase(\"")).output(mark("name", "FirstLowerCase")).output(literal("\")) this.")).output(mark("name", "javaValidName", "FirstLowerCase", "javaValidWord")).output(literal(" = (")).output(mark("type")).output(literal(") values.get(0);")),
				rule().condition((allTypes("owner", "reactive", "variable")), not(anyTypes("inherited", "overriden")), (trigger("set"))).output(literal("if (name.equalsIgnoreCase(\"")).output(mark("name", "FirstLowerCase")).output(literal("\")) this.")).output(mark("name", "javaValidName", "FirstLowerCase", "javaValidWord")).output(literal(" = io.intino.tara.magritte.loaders.FunctionLoader.load(values.get(0), this, io.intino.tara.magritte.Expression.class);")),
				rule().condition((allTypes("owner", "function", "variable")), not(anyTypes("inherited", "overriden")), (trigger("set"))).output(literal("if (name.equalsIgnoreCase(\"")).output(mark("name", "FirstLowerCase")).output(literal("\")) this.")).output(mark("name", "javaValidName", "FirstLowerCase", "javaValidWord")).output(literal(" = io.intino.tara.magritte.loaders.FunctionLoader.load(values.get(0), this, ")).output(mark("workingPackage")).output(literal(".functions.")).output(mark("rule", "interfaceClass")).output(literal(".class);")),
				rule().condition((allTypes("owner", "variable", "multiple", "time")), not(anyTypes("reactive", "inherited", "overriden")), (trigger("set"))).output(literal("if (name.equalsIgnoreCase(\"")).output(mark("name", "FirstLowerCase")).output(literal("\")) this.")).output(mark("name", "javaValidName", "FirstLowerCase", "javaValidWord")).output(literal(" = new java.util.ArrayList<>((List<java.time.LocalTime>) values);")),
				rule().condition((allTypes("owner", "variable", "multiple")), not(anyTypes("reactive", "inherited", "overriden")), (trigger("set"))).output(literal("if (name.equalsIgnoreCase(\"")).output(mark("name", "FirstLowerCase")).output(literal("\")) this.")).output(mark("name", "javaValidName", "FirstLowerCase", "javaValidWord")).output(literal(" = new java.util.ArrayList<>((java.util.List<")).output(mark("type", "fullType")).output(literal(">) values);")),
				rule().condition((allTypes("owner", "variable")), not(anyTypes("reactive", "inherited", "concept", "multiple", "overriden")), (trigger("set"))).output(literal("if (name.equalsIgnoreCase(\"")).output(mark("name", "FirstLowerCase")).output(literal("\")) this.")).output(mark("name", "javaValidName", "FirstLowerCase", "javaValidWord")).output(literal(" = (")).output(mark("type", "fullType")).output(literal(") values.get(0);"))
		);
	}
}