{
  parserClass='monet.tara.metamodelplugin.TaraParser'
  stubParserClass='monet.tara.metamodelplugin.parser.GeneratedParserUtilBase'

  extends='com.intellij.extapi.psi.ASTWrapperPsiElement'

  psiClassPrefix='Tara'
  psiImplClassSuffix='Impl'
  psiPackage='monet.tara.metamodelplugin.psi'
  psiImplPackage='monet.tara.metamodelplugin.psi.impl'

  elementTypeHolderClass='monet.tara.metamodelplugin.psi.TaraTypes'
  elementTypeClass='monet.tara.metamodelplugin.psi.TaraElementType'
  tokenTypeClass='monet.tara.metamodelplugin.psi.TaraTokenType'

  psiImplUtilClass='monet.tara.metamodelplugin.psi.impl.TaraPsiImplUtil'
}

root ::=(COMMENT|conceptDefinition)+

conceptDefinition ::= conceptSignature conceptBlock? END_CONCEPT {mixin='monet.tara.metamodelplugin.psi.impl.TaraNamedElementImpl' implements='monet.tara.metamodelplugin.psi.TaraNamedElement' methods=[getIdentifier getName setName getNameIdentifier]}

conceptSignature ::= CONCEPT MODIFIERS? IDENTIFIER (IS IDENTIFIER)? annotation*

conceptBlock::= INDENT statement+ DEDENT

statement::= propertiesBody | childrenBody | referencesBody

propertiesBody::=primitive_type IDENTIFIER (ASSIGN primitive)?

childrenBody::=HAS IDENTIFIER annotation* conceptBlock*

referencesBody::=REF IDENTIFIER {methods=[getIdentifier]}

primitive_type ::=  ID_TYPE|INT_TYPE|STRING_TYPE|DOUBLE_TYPE

primitive ::=  INT|DOUBLE|STRING

annotation ::= NAMEABLE|AT_ROOT|EXTENSIBLE|ACTION

