package tara.dsl;

import tara.language.model.Tag;

import java.util.Locale;

import static tara.language.semantics.constraints.RuleFactory.*;

public class Sumus extends Tara {
	public Sumus() {
		in("").def(context("").allow(multiple("Producer", Tag.MAIN, Tag.TERMINAL_INSTANCE), multiple("Classifier", Tag.MAIN, Tag.TERMINAL_INSTANCE), multiple("Record", Tag.MAIN), multiple("Member", Tag.MAIN), multiple("Fact", Tag.MAIN), multiple("Source"), multiple("Dashboard", Tag.TERMINAL_INSTANCE, Tag.MAIN), name()).doc("sumusnew.Sumus", 0, ""));
		in("Producer").def(context("Concept").allow(multiple("Selection", Tag.TERMINAL_INSTANCE), multiple("Ratio", Tag.TERMINAL_INSTANCE), name()).assume(isMain(), isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Query.tara", 5, ""));
		in("Selection").def(context("Concept").allow(name()).require(oneOf(_single("Selection.Count"), _single("Selection.Total"), _single("Selection.Average")), _parameter("record", new String[]{"Member", "Fact", "Record"}, false, 0, "", "FINAL", "TERMINAL"), _parameter("label", "string", false, 1, "", "TERMINAL")).assume(isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Query.tara", 9, ""));
		in("Selection.Count").def(context("Concept").allow(name()).assume(isFeatureInstance(), isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Query.tara", 13, ""));
		in("Selection.Total").def(context("Concept").allow(name()).require(_parameter("attribute", "native", false, 0, "Attribute#public Object get(Record item)", "FINAL", "TERMINAL")).assume(isFeatureInstance(), isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Query.tara", 14, ""));
		in("Selection.Average").def(context("Concept").allow(name()).require(_parameter("attribute", "native", false, 0, "Attribute#public Object get(Record item)", "FINAL", "TERMINAL")).assume(isFeatureInstance(), isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Query.tara", 16, ""));
		in("Ratio").def(context("Concept").allow(name()).require(_parameter("numerator", new String[]{"Selection", "Ratio"}, false, 0, "", "TERMINAL"), _parameter("denominator", new String[]{"Selection", "Ratio"}, false, 1, "", "TERMINAL")).assume(isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Query.tara", 18, ""));
		in("Classifier").def(context("Concept").allow(multiple("Classification", Tag.TERMINAL_INSTANCE, Tag.FINAL), name()).assume(isMain(), isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Query.tara", 23, ""));
		in("Classification").def(context("Concept").allow(multiple("Classification", Tag.TERMINAL_INSTANCE), single("Classification.Ordinal", Tag.SINGLE, Tag.FEATURE_INSTANCE, Tag.TERMINAL_INSTANCE), single("Classification.Nominal", Tag.SINGLE, Tag.FEATURE_INSTANCE, Tag.TERMINAL_INSTANCE), single("Classification.Ordinal", Tag.SINGLE, Tag.FEATURE_INSTANCE, Tag.TERMINAL_INSTANCE), single("Classification.Nominal", Tag.SINGLE, Tag.FEATURE_INSTANCE, Tag.TERMINAL_INSTANCE), name()).require(_parameter("record", new String[]{"Member", "Fact", "Record"}, false, 0, "", "FINAL", "TERMINAL"), _parameter("label", "string", false, 1, "", "FINAL", "TERMINAL")).assume(isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Query.tara", 26, ""));
		in("Classification.Ordinal").def(context("Concept").allow(parameter("mode:word", new String[]{"Ascending", "Descending"}, false, 1, "", "FINAL", "TERMINAL"), name()).require(_parameter("attribute", "native", false, 0, "Attribute#public Object get(Record item)", "FINAL", "TERMINAL")).assume(isFeatureInstance(), isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Query.tara", 32, ""));
		in("Classification.Nominal").def(context("Concept").allow(name()).require(_multiple("Classification.Nominal.Category"), _parameter("attribute", "native", false, 0, "Attribute#public Object get(Record item)", "FINAL", "TERMINAL")).assume(isFeatureInstance(), isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Query.tara", 34, ""));
		in("Classification.Nominal.Category").def(context("Concept").allow(multiple("Classification.Nominal.Category", Tag.REQUIRED, Tag.TERMINAL_INSTANCE), parameter("check", "native", false, 1, "Check#public boolean check(Object value)", "FINAL", "TERMINAL"), name()).require(_parameter("label", "string", false, 0, "", "FINAL", "TERMINAL")).assume(isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Query.tara", 35, ""));
		in("Record").def(context("Concept").allow(name()).assume(isMain()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Main.tara", 3, ""));
		in("Member").def(context("Concept").allow(parameter("label", "string", false, 0, "", "TERMINAL"), name()).assume(isMain()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Main.tara", 5, ""));
		in("Fact").def(context("Concept").allow(multiple("Record", Tag.MAIN), parameter("instant", "date", false, 0, "", "TERMINAL"), name()).assume(isMain()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Main.tara", 8, ""));
		in("Source").def(context("Concept").allow(multiple("Source.Context", Tag.FEATURE_INSTANCE), name()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Main.tara", 12, ""));
		in("Source.Context").def(context("Concept").allow(name()).require(_parameter("execute", "native", false, 0, "Execute#public void execute()")).assume(isFeatureInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Main.tara", 13, ""));
		in("Dashboard").def(context("Concept").allow(multiple("Dashboard.BarChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.ColumnChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.LineChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AreaChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PieChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PercentageArea", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.BubbleChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.HeatMap", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SpiderWeb", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.WindRose", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AngularGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SolidGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.VuMeter", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.BarChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.ColumnChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.LineChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AreaChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.BarChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.ColumnChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.LineChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AreaChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PieChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PercentageArea", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.BubbleChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.HeatMap", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SpiderWeb", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.WindRose", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AngularGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SolidGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.VuMeter", Tag.FINAL, Tag.TERMINAL_INSTANCE), single("Dashboard.Timeline", Tag.SINGLE, Tag.FINAL, Tag.TERMINAL_INSTANCE), parameter("layout", "string", false, 1, "", "TERMINAL"), name()).require(_parameter("label", "string", false, 0, "", "TERMINAL")).assume(isTerminalInstance(), isMain()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Visualization.tara", 5, ""));
		in("Dashboard.Timeline").def(context("Concept").allow(name()).require(_parameter("scales:word", new String[]{"Year", "Quarter", "Season", "Month", "Week", "Day", "Hour", "Minute", "Second"}, true, 0, "", "TERMINAL")).assume(isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Visualization.tara", 8, ""));
		in("Dashboard.Chart.Display").def(context("Concept").allow(single("Dashboard.Chart.Display.ColorScheme", Tag.SINGLE, Tag.FINAL, Tag.TERMINAL_INSTANCE), parameter("subtitle", "string", false, 1, "", "TERMINAL"), name()).require(_parameter("title", "string", false, 0, "", "TERMINAL")).assume(isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Visualization.tara", 14, ""));
		in("Dashboard.Chart.Display.ColorScheme").def(context("Concept").allow(name()).require(_parameter("colors", "integer", true, 0, "", "TERMINAL")).assume(isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Visualization.tara", 17, ""));
		in("Dashboard.BarChart").def(context("Concept").allow(multiple("Dashboard.BarChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.ColumnChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.LineChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AreaChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PieChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PercentageArea", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.BubbleChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.HeatMap", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SpiderWeb", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.WindRose", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AngularGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SolidGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.VuMeter", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.Chart.Display", Tag.TERMINAL_INSTANCE), parameter("drill", new String[]{"Classification"}, false, 2, "", "FINAL", "TERMINAL"), name()).require(_parameter("selection", new String[]{"Selection", "Ratio"}, false, 0, "", "TERMINAL"), _parameter("axis", new String[]{"Classification"}, false, 1, "", "FINAL", "TERMINAL")).assume(isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Visualization.tara", 24, ""));
		in("Dashboard.ColumnChart").def(context("Concept").allow(multiple("Dashboard.BarChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.ColumnChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.LineChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AreaChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PieChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PercentageArea", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.BubbleChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.HeatMap", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SpiderWeb", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.WindRose", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AngularGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SolidGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.VuMeter", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.Chart.Display", Tag.TERMINAL_INSTANCE), parameter("drill", new String[]{"Classification"}, false, 2, "", "FINAL", "TERMINAL"), name()).require(_parameter("selection", new String[]{"Selection", "Ratio"}, false, 0, "", "TERMINAL"), _parameter("axis", new String[]{"Classification"}, false, 1, "", "FINAL", "TERMINAL")).assume(isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Visualization.tara", 26, ""));
		in("Dashboard.LineChart").def(context("Concept").allow(multiple("Dashboard.BarChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.ColumnChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.LineChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AreaChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PieChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PercentageArea", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.BubbleChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.HeatMap", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SpiderWeb", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.WindRose", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AngularGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SolidGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.VuMeter", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.Chart.Display", Tag.TERMINAL_INSTANCE), parameter("drill", new String[]{"Classification"}, false, 2, "", "FINAL", "TERMINAL"), parameter("mode:word", new String[]{"Default", "StepLeft", "StepCenter", "StepRight", "Spline"}, false, 3, "", "TERMINAL"), name()).require(_parameter("selection", new String[]{"Selection", "Ratio"}, false, 0, "", "TERMINAL"), _parameter("axis", new String[]{"Classification"}, false, 1, "", "FINAL", "TERMINAL")).assume(isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Visualization.tara", 28, ""));
		in("Dashboard.AreaChart").def(context("Concept").allow(multiple("Dashboard.BarChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.ColumnChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.LineChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AreaChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PieChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PercentageArea", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.BubbleChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.HeatMap", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SpiderWeb", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.WindRose", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AngularGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SolidGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.VuMeter", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.Chart.Display", Tag.TERMINAL_INSTANCE), parameter("drill", new String[]{"Classification"}, false, 2, "", "FINAL", "TERMINAL"), name()).require(_parameter("selection", new String[]{"Selection", "Ratio"}, false, 0, "", "TERMINAL"), _parameter("axis", new String[]{"Classification"}, false, 1, "", "FINAL", "TERMINAL")).assume(isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Visualization.tara", 31, ""));
		in("Dashboard.PieChart").def(context("Concept").allow(multiple("Dashboard.BarChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.ColumnChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.LineChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AreaChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PieChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PercentageArea", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.BubbleChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.HeatMap", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SpiderWeb", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.WindRose", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AngularGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SolidGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.VuMeter", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.Chart.Display", Tag.TERMINAL_INSTANCE), name()).require(_parameter("selection", new String[]{"Selection", "Ratio"}, false, 0, "", "TERMINAL"), _parameter("drill", new String[]{"Classification"}, false, 1, "", "FINAL", "TERMINAL")).assume(isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Visualization.tara", 33, ""));
		in("Dashboard.PercentageArea").def(context("Concept").allow(multiple("Dashboard.BarChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.ColumnChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.LineChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AreaChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PieChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PercentageArea", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.BubbleChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.HeatMap", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SpiderWeb", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.WindRose", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AngularGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SolidGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.VuMeter", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.Chart.Display", Tag.TERMINAL_INSTANCE), name()).require(_parameter("selection", new String[]{"Selection", "Ratio"}, false, 0, "", "TERMINAL")).assume(isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Visualization.tara", 36, ""));
		in("Dashboard.BubbleChart").def(context("Concept").allow(multiple("Dashboard.BarChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.ColumnChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.LineChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AreaChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PieChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PercentageArea", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.BubbleChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.HeatMap", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SpiderWeb", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.WindRose", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AngularGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SolidGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.VuMeter", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.Chart.Display", Tag.TERMINAL_INSTANCE), name()).require(_parameter("selection", new String[]{"Selection", "Ratio"}, false, 0, "", "TERMINAL"), _parameter("classification", new String[]{"Classification"}, true, 1, "", "FINAL", "TERMINAL")).assume(isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Visualization.tara", 37, ""));
		in("Dashboard.HeatMap").def(context("Concept").allow(multiple("Dashboard.BarChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.ColumnChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.LineChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AreaChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PieChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PercentageArea", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.BubbleChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.HeatMap", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SpiderWeb", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.WindRose", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AngularGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SolidGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.VuMeter", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.Chart.Display", Tag.TERMINAL_INSTANCE), name()).require(_parameter("selection", new String[]{"Selection", "Ratio"}, false, 0, "", "TERMINAL")).assume(isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Visualization.tara", 40, ""));
		in("Dashboard.SpiderWeb").def(context("Concept").allow(multiple("Dashboard.BarChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.ColumnChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.LineChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AreaChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PieChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PercentageArea", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.BubbleChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.HeatMap", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SpiderWeb", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.WindRose", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AngularGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SolidGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.VuMeter", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.Chart.Display", Tag.TERMINAL_INSTANCE), name()).require(_parameter("selection", new String[]{"Selection", "Ratio"}, false, 0, "", "TERMINAL")).assume(isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Visualization.tara", 41, ""));
		in("Dashboard.WindRose").def(context("Concept").allow(multiple("Dashboard.BarChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.ColumnChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.LineChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AreaChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PieChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PercentageArea", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.BubbleChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.HeatMap", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SpiderWeb", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.WindRose", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AngularGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SolidGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.VuMeter", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.Chart.Display", Tag.TERMINAL_INSTANCE), name()).require(_parameter("selection", new String[]{"Selection", "Ratio"}, false, 0, "", "TERMINAL")).assume(isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Visualization.tara", 42, ""));
		in("Dashboard.AngularGauge").def(context("Concept").allow(multiple("Dashboard.BarChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.ColumnChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.LineChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AreaChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PieChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PercentageArea", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.BubbleChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.HeatMap", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SpiderWeb", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.WindRose", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AngularGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SolidGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.VuMeter", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.Chart.Display", Tag.TERMINAL_INSTANCE), name()).require(_parameter("selection", new String[]{"Selection", "Ratio"}, false, 0, "", "TERMINAL")).assume(isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Visualization.tara", 43, ""));
		in("Dashboard.SolidGauge").def(context("Concept").allow(multiple("Dashboard.BarChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.ColumnChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.LineChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AreaChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PieChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PercentageArea", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.BubbleChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.HeatMap", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SpiderWeb", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.WindRose", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AngularGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SolidGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.VuMeter", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.Chart.Display", Tag.TERMINAL_INSTANCE), name()).require(_parameter("selection", new String[]{"Selection", "Ratio"}, false, 0, "", "TERMINAL")).assume(isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Visualization.tara", 44, ""));
		in("Dashboard.VuMeter").def(context("Concept").allow(multiple("Dashboard.BarChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.ColumnChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.LineChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AreaChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PieChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.PercentageArea", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.BubbleChart", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.HeatMap", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SpiderWeb", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.WindRose", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.AngularGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.SolidGauge", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.VuMeter", Tag.FINAL, Tag.TERMINAL_INSTANCE), multiple("Dashboard.Chart.Display", Tag.TERMINAL_INSTANCE), name()).require(_parameter("selection", new String[]{"Selection", "Ratio"}, false, 0, "", "TERMINAL")).assume(isTerminalInstance()).doc("/Users/octavio/workspace/sandbox/sumusnew/Base/model/Visualization.tara", 45, ""));
	}

	@Override
	public String languageName() {
		return "Sumus";
	}

	@Override
	public Locale locale() {
		return Locale.ENGLISH;
	}

	@Override
	public boolean isTerminalLanguage() {
		return false;
	}
}
